### ISSUE TITLE
Maybe a bug: samples in the heatmap were less than expected

### ISSUE THREAD

**Issue by btrspg** [zqfang/GSEApy#100]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import gseapy; print(gseapy.__version__)
```
3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
CPython
Darwin-19.4.0-x86_64-i386-64bit
0.9.18

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

```python
print(len(mylist))
results = gseapy.gsea(data=data,
                          gene_sets='kegg.gmt',
                          cls=mylist,
                          permutation_num=1,
                          outdir=outdir + '/' + mc.replace(' ', '_'),
                          permutation_type='gene_set',
                          processes=10,
                          no_plot=False)
print(results.heatmat.shape)
```
I thought the sample number should be the same, but it is not.

```
161
2020-05-03 22:43:24,106 Warning: dropping duplicated gene names, only keep the first values
2020-05-03 22:43:24,187 Warning: Input data contains NA, filled NA with 0
(7479, 152)
```

It will be less than total samples in my data. Is this a bug or some pre-processes that remove some samples?

**Comment by zqfang** [comment]
@btrspg  how many groups in your input cls_vector? Now only supoort 2 groups

**Comment by btrspg** [comment]
@zqfang More than 2 groups, so I need to modified them into 2 groups?

**Comment by zqfang** [comment]
@btrspg , You'er right. Anyway, I'll add warnings if not exactly 2 group

**Comment by btrspg** [comment]
@zqfang Thanks.
