### ISSUE TITLE
Ranking by absolute value of signal to noise

### ISSUE THREAD

**Issue by caleb-lindgren** [zqfang/GSEApy#102]
I recently read the article ["Ranking metrics in gene set enrichment analysis: do they matter?"](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1674-0#Tab3), where they compare 16 different ranking metrics commonly used in GSEA. One of the 4 methods they rated the best was the absolute value of the signal-to-noise ratio. 

Looking at your package, I see that you already provide the signal-to-noise ratio as an option for the ranking metric. What do you think of adding the absolute value of it as another option? Doing so would be easy; all you would need to do is copy [this line of code](https://github.com/zqfang/GSEApy/blob/master/gseapy/algorithm.py#L236) in the gseapy/algorithm.py file, and add an absolute value around it:
```
...
elif method == 'abs_signal_to_noise':
        cor_mat = abs((pos_cor_mean - neg_cor_mean)/(pos_cor_std + neg_cor_std))
...
```

I'd be happy to help, if you'd like to do this. Thanks!

**Comment by caleb-lindgren** [comment]
I missed one part--you'd also need to add this similar code to line 312 of gseapy/algorithm.py:
```
elif method == 'abs_signal_to_noise':
    ser = abs((df_mean[pos] - df_mean[neg])/(df_std[pos] + df_std[neg]))
```

**Comment by zqfang** [comment]
ranking method added. Thank you very much for your suggestion

**Comment by caleb-lindgren** [comment]
Great! Looks good to me.
