### ISSUE TITLE
Prerank returns a value of infinity for NES when using weighted_score_type == 1

### ISSUE THREAD

**Issue by scottdtaylor95** [zqfang/GSEApy#105]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]
CPython
Linux-5.4.0-42-generic-x86_64-with-glibc2.29
0.9.19

### Issue

When prerank is run on my data set using the defaults and the enrichr libraries 'ARCHS4_Tissues' and 'KEGG_2019_Human' (and possibly with other libraries), the nes value returned for some gene sets is sometimes inf or a very large value (in the thousands). The fdr value is also sometimes over 1 - showing as 1e9.  However, when the weighted_score_type is 0, this issue does not seem to occur. 

Would you be able to identify if there's a particular issue that causes this? Much thanks!

### Steps to reproduce

An example of the input data is attached. This can be run through prerank with defaults (although max_size may need to be increased)
[Example_input.xlsx](https://github.com/zqfang/GSEApy/files/5039754/Example_input.xlsx)

**Comment by zqfang** [comment]
Thank you for reporting this. If you see FDR = 1e9, it means there's something wrong with the FDR calculation. Now, the NES should make sense now. By the way, your input gene list are really big.

**Comment by scottdtaylor95** [comment]
Thank you so much for replying and fixing the issue. I know the input list is rather large, as we are looking at "scores" across RNAseq results. Is the size of the list an issue? If so, is there a recommended method to use or way to reduce/filter the list? Thanks again, I will install and try the new version.

**Comment by zqfang** [comment]
No an issue if your computer has enough memory. You could just use differentially expressed gene list to make computation faster.

**Comment by scottdtaylor95** [comment]
I reran using the new version and while the FDR is within normal limits, the NES now shows up as NaN and I received this new error: gseapy/algorithm.py:541: RuntimeWarning: Mean of empty slice.
  esnull_pos.append(enrNull[enrNull >= 0].mean()).

**Comment by zqfang** [comment]
IWhat's your command? It seem that you did not have enough permutation

**Comment by scottdtaylor95** [comment]
Ah, I see. I ran it with 1000 permutations, but my data is fairly skewed negatively.
