### ISSUE TITLE
Enrichr API key error

### ISSUE THREAD

**Issue by t-silvers** [zqfang/GSEApy#111]
Thanks for this great tool.

When using `gp.enrichr` and running the following command (with args taken from docs to illustrate)
```
gene_list=['IGKV4-1', 'CD55', 'IGKC', 'PPFIBP1', 'ABHD4', 'PCSK6', 'PGD', 'ARHGDIB', 'ITGB2', 'CARD6']
enr = gp.enrichr(gene_list=gene_list,
                  gene_sets=['KEGG_2016','KEGG_2013'],
                  organism='Human', # don't forget to set organism to the one you desired! e.g. Yeast
                  description='test_name',
                  outdir='test/enrichr_kegg',
                  no_plot=True,
                  cutoff=0.5 # test dataset, use lower value from range(0,1)
                  )
```
I get a `KeyError: 'userListId'` error [traceable to the Enrichr API](https://github.com/zqfang/GSEApy/blob/a35277fd412bb9adfdeb6bdcd4732ff9c27d866d/gseapy/enrichr.py#L171).

I've used Enrichr for a while now and know changes to the Enrichr API have caused issues before. It looks like the url is responding, but the field 'userListId' is absent.

**Comment by fvalle1** [comment]
I noticed the same error

**Comment by SaBay89** [comment]
I like GSEApy and thank you for this great tool :)
Unfortunately, I have the same issue.
Hopefully, it is fixed as soon as possible

**Comment by fvalle1** [comment]
#112 should fix this

**Comment by SaBay89** [comment]
> #112 should fix this

Great job :)
It works
