### ISSUE TITLE
GSEApy "KeyError: 'Adjusted P-value'"

### ISSUE THREAD

**Issue by bromleyjd** [zqfang/GSEApy#116]
I've been able to use GSEApy without any problems for several months, as of a couple days ago I keep getting the error: KeyError: 'Adjusted P-value'. Is this a recent bug? Any tips on how to get around this?

This is the code where I get an error:
enr = gp.enrichr(gene_list=diff_genes, organism='Human',gene_sets=['KEGG_2016'], cutoff=0.5)

This is what the error output: 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3079             try:
-> 3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Adjusted P-value'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-6-24a5f21e3da9> in <module>
      7 diff_genes = pd.DataFrame(adata_raw.uns['rank_genes_groups']['names']).iloc[0:pval_cutoff,i]
      8 
----> 9 enr = gp.enrichr(gene_list=diff_genes, organism='Human',gene_sets=['KEGG_2016'], cutoff=0.5)
     10 gp.dotplot(enr.results, title='leiden_lab_Pheno', figsize=(4,8), cutoff=0.10, top_term=30)

~/opt/anaconda3/lib/python3.8/site-packages/gseapy/enrichr.py in enrichr(gene_list, gene_sets, organism, description, outdir, background, cutoff, format, figsize, top_term, no_plot, verbose)
    430     enr = Enrichr(gene_list, gene_sets, organism, description, outdir,
    431                   cutoff, background, format, figsize, top_term, no_plot, verbose)
--> 432     enr.run()
    433 
    434     return enr

~/opt/anaconda3/lib/python3.8/site-packages/gseapy/enrichr.py in run(self)
    381             # plotting
    382             if not self.__no_plot:
--> 383                 msg = barplot(df=res, cutoff=self.cutoff, figsize=self.figsize,
    384                               top_term=self.__top_term, color='salmon',
    385                               title=self._gs,

~/opt/anaconda3/lib/python3.8/site-packages/gseapy/plot.py in barplot(df, column, title, cutoff, top_term, figsize, color, ofname, **kwargs)
    498     if colname in ['Adjusted P-value', 'P-value']:
    499         # check if any values in `df[colname]` can't be coerced to floats
--> 500         can_be_coerced = df[colname].map(isfloat)
    501         if np.sum(~can_be_coerced) > 0:
    502             raise ValueError('some value in %s could not be typecast to `float`'%colname)

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3022             if self.columns.nlevels > 1:
   3023                 return self._getitem_multilevel(key)
-> 3024             indexer = self.columns.get_loc(key)
   3025             if is_integer(indexer):
   3026                 indexer = [indexer]

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 
   3084         if tolerance is not None:

KeyError: 'Adjusted P-value'

**Comment by zqfang** [comment]
It looks like the some data are lost during the internet connection. Sorry,  I could not reproduce the issue. 

You could set `no_plot=True`, get the dataframe, and plot the results using `seaborn`.
