### ISSUE TITLE
Prerank step takes an incredible volume of memory

### ISSUE THREAD

**Issue by PeifengJi** [zqfang/GSEApy#134]
Hi GSEApy developer:
     First, thank for developing GSEApy, it's every useful.
     Currently, I am running the prerank step to perform enrichment against the C7 database.
     It take  an incredible volume of memory (up to 300 Gb). My commands are as follows:

import gseapy as gs
import numpy as np
import pandas as pd

def enrich(df, directory):
    libdir = '/singleCell/public_data/msigdb_rat'
    hallmark = libdir + '/' + 'h.all.v7.1.symbols.gmt'
    c5 = libdir + '/' + 'c5.all.v7.1.symbols.gmt'
    c7 = libdir + '/' + 'c7.all.v7.1.symbols.gmt'
    c2 =  libdir + '/' + 'c2.all.v7.1.symbols.gmt'
    print('Immune')
    pre_res = gs.prerank(rnk=tmp, gene_sets=c7, processes=10, permutation_num=1000)
    terms = pre_res.res2d
    res = terms[terms['fdr']<0.05].reset_index()
    res.to_csv(f'{directory}/immuno.csv')
    # KEGG
    print('KEGG')
    pre_res = gs.prerank(rnk=tmp, gene_sets=c2, processes=10, permutation_num=1000)
    terms = pre_res.res2d
    res = terms[terms['fdr']<0.05].reset_index()
    res.to_csv(f'{directory}/kegg.csv')

print('Reading files...')
directory = './'
df = pd.read_csv('Region4_vs_Region1_DEGs.csv')
enrich(df, directory)

My GSEApy version is 0.10.5. Can you figure out the problem?
Thank you!

**Comment by zqfang** [comment]
Any upcoming release of GSEApy which re-written in Rust will over come the problem. Stay tune!

**Comment by zqfang** [comment]
The Rust binding of GSEApy (v0.11.0) has been released. Close the issue now
