### ISSUE TITLE
Confusion regarding phenotype permutation

### ISSUE THREAD

**Issue by pirakd** [zqfang/GSEApy#140]
Hello,
I am having difficulties to understand where do  random permutations are calculated and stored in phenotype permutation mode. As I understand the code this is supposed to be done in [line 372 ](https://github.com/zqfang/GSEApy/blob/60612ff799098405a97ae583e344a6f8e9c94534/gseapy/algorithm.py#L372)
But instead of sending the required permutation number it sends the variable "base".
Eventually when in [396](https://github.com/zqfang/GSEApy/blob/73e425d9ff9ddc1b7d1a865fa6aa32027d143ffa/gseapy/algorithm.py#L396) significance is computed, esnull is of size (num_pathways, 5).
What am I missing?

I am running gseapy.gsea  as follows:
`a= gs.gsea(data='P53.txt', gene_sets='pathway.gmt', cos='P53.cls', method='s2n', outdir='test', permutation_num=1000,  permutation_type='phenotype')`

All files are in format.
Thanks!

Edit:
For simplicity I entered a single pathway in pathway.gmt but strangely, I get different number of nulls per pathway for different number of pathways in the gmt file.

**Comment by zqfang** [comment]
see the line 384, the blocks will be stacked back to the permutation_num.
```
genes_ind, cor_mat = np.vstack(genes_ind), np.vstack(cor_mat)
```

Let permutation_num = 50, then a 3d tensor with shape (1000, 20, 50), aka (genes, samples, permutation_num) 
will probably cost a lot of memroy.

To reduce the memory costs, split 50 into 10 blocks (50 / 5), aka, each block with shape (1000, 20, 5), then permute

The last step is (line 384) will combine all permuated data 


Hope it helps

**Comment by pirakd** [comment]
Thanks for the quick reply! 

I would accept your answer if "blocks" would be defined as:
'block = ceil(n_permutations / base)'
but instead it is:
`block = ceil(len(subsets) / base)` 
Where "subsets" is the number of sets in the .gmt dataset.
I don't understand how this gives the correct number of permutations. 

And not matter where and how we permute, don't i suppose to receive 1000 null values? Because this is not what i am getting (i am getting base*blocks permutations).

**Comment by zqfang** [comment]
It's the same idea if you have 1000 gene_sets: reducing your memory cost

**Comment by zqfang** [comment]
It works fine now. @pirakd
