### ISSUE TITLE
issue with biomart

### ISSUE THREAD

**Issue by LeilyR** [zqfang/GSEApy#144]
print(gp.__version__)
python : 3.8
matplotlib: 3.3.2

from gseapy.parser import Biomart
bm = Biomart()

returns the following error:

/localenv/usr/anaconda/miniconda3/envs/matplotlib/lib/python3.8/site-packages/easydev/logging_tools.py in _set_level(self, level)
     78         assert level in ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],\
     79             "you provided {}".format(level)
---> 80         logging_level = getattr(colorlog.logging.logging, level)
     81         colorlog.getLogger(self.name).setLevel(level)
     82 

is it because of some restriction on the version of depending tools? I appreciate your input

**Comment by zqfang** [comment]
It looks like the bioservices issue. Did you have the full error records?
