### ISSUE TITLE
How can I produce gsea reports for positive and negative for cytoscape?

### ISSUE THREAD

**Issue by daschukds** [zqfang/GSEApy#147]
Hello. Thanks for this great py.

I have 2 questions.
1. How can I produce gsea reports for positive and negative for cytoscape? Desktop version of GSEA produce 'gsea_report_for_na_neg_1650562911301.tsv' and 'gsea_report_for_na_pos_1650562911301.tsv' which will be used as input for cytoscape.  However, py version does not produce these files. instead, py version produce gsea_report for all pos and neg with different column names and column info. There must be an option for these. 

2. How can I produce edb file? I followed the example on https://gseapy.readthedocs.io/en/latest/gseapy_example.html#4.-GSEA-Example. This does not explain the option to make edb file. Can you help me?

Sincerely,

**Comment by zqfang** [comment]
1. Would you mind send me a copy of "gsea_report_for_na_neg_1650562911301.tsv", I could make this extension 

I'm not sure why you need the edb file? You have to generate the edb file by yourself ( export the xml format file)

**Comment by daschukds** [comment]
Hi. I was trying to make enrichment map using cytoscape 'enrichment map'. Enrichment map in the cytoscape accepts the results from desktop version. When I used the gseapy.gsea.phenotype.report.csv from gseapy, cytoscape popped up an error message like I need to provide correct input data. I was wondering if there is a way to generate the report file that can be accepted to 'Enrichment map' in cytoscape.

Sincerely,

**Comment by zqfang** [comment]
Correctly, GSEApy could not support to enrichmap. However, I think you could do it using networkx easy. 

- node: enriched terms
- node_size: pvalue/fdr/nes
- color: pvalue/fdr/nes
- edge: any two enriched terms have more than 1 genes overlapped
- edge_weight: number of overlapped genes of any two enriched terms

**Comment by daschukds** [comment]
OK. Thanks for confirming it. I will try networkx. But i wish gseapy could support enrichmap in the future because its easier to redraw the network using mouse rather than changing coordination numbers.

**Comment by zqfang** [comment]
Sorry. It's long overdue. Now with v1.0.1. You can export networks for cytoscape, networkx via `enrichment_map` function
