### ISSUE TITLE
dotplot Error in line 396 in plot.py

### ISSUE THREAD

**Issue by solo7773** [zqfang/GSEApy#150]
When run `dotplot(enr.res2d, ...)`, I got this error `KeyError: 'Combined Score'`.

I checked the plot.py and in line 396, it is

```
combined_score = df['Combined Score'].round().astype('int')
```

I am using gseapy 0.10.8. Columns are

```['Gene_set', 'Term', 'Overlap', 'P-value', 'Adjusted P-value', 'Odds Ratio', 'Genes']```

I think "Odds Ratio" = "Combined Score"

Please help to fix this error.

**Comment by zqfang** [comment]
Sorry for replying late. "Combine Score" is generated from Enrichr API. Now it's fixed
