### ISSUE TITLE
Logging.__init__() got an unexpected keyword argument 'text_color'

### ISSUE THREAD

**Issue by LCLazari** [zqfang/GSEApy#151]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
R: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
import platform; print(platform.python_implementation()); print(platform.platform())
R: CPython; Windows-10-10.0.19044-SP0
import gseapy; print(gseapy.__version__)
R: Can't import, returns error in title.
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour
*gseapy import to work*
(*Please fill this in*)

### Actual behaviour
*Logging.__init__() got an unexpected keyword argument 'text_color'*
(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce
*import gseapy*
(*Please fill this in*)

**Comment by zqfang** [comment]
It looks like a bug from logging module
