### ISSUE TITLE
Exeption: Error analyzing gene list 

### ISSUE THREAD

**Issue by robbiepope** [zqfang/GSEApy#153]
I am currently trying to run a GSEA for ~450 gene sets (all gene lists contain >25 genes). I previously ran the analysis (for loop with enrichr function calling each list) without any issues at the beginning of 2022 (Feb). However, recently when I have tried to repeat the analysis I am met with the error 'Error analyzing gene list' at different points in the loop. After a couple of tests, the specific gene list raising the error was different each time and the index of the list causing the error varied from 50-320. When the specific gene list was analysed individually, it did not raise an error. The dataset is the same that was used in Feb 2022 which ran without errors.

After reviewing the similar issue raised (#117) where the enrichr server could sometimes not be reached, I added a 5 second delay to my for loop between each call but unfortunately this hasn't resolved the issue for me. I also tried splitting the list of gene sets into smaller lists to run individually however, as I am not sure how many calls to the enrichr server may cause the error I have not had much luck with this approach. 

Do you have any advice of what I could try to prevent this issue from occurring?

GSEAPY Version: 0.10.8
Python 3.10

GSEA function:
<img width="684" alt="Screenshot 2022-07-09 at 17 59 41" src="https://user-images.githubusercontent.com/99690508/178115646-eb954490-672d-4c60-9195-3bf0e7a8ee78.png">
![Screenshot 2022-07-09 at 18 01 18](https://user-images.githubusercontent.com/99690508/178115682-b2859bb4-911c-41a5-8bb2-b7291f90b328.png)

**Comment by zqfang** [comment]
Better to download the 'GO_Biological_Process_2021.gmt' file first

So you won't be blocked
