### ISSUE TITLE
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

### ISSUE THREAD

**Issue by snewhouse** [zqfang/GSEApy#157]
- gseapy/enrichr.py:427: **FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.**

I get this warning. Any plans to update .append to .concat?

**Comment by zqfang** [comment]
The lastest release v0.11.0 is already fixed this warning. Please use this version for you GSEA analysis, it's much more efficient than before
