### ISSUE TITLE
prerank input

### ISSUE THREAD

**Issue by wangjiawen2013** [zqfang/GSEApy#158]
Hi, 
I tried prerank() in gseapy and I am not sure how to prepare the input dataframe. Is it necessary to sort the input dataframe in descending order ? Or gseapy will sort it internally ?
Besides, what if the genes in the input dataframe have the same value (such as logfoldchange, p-value) ?
I input a gene list with the same value, and gseapy prerank returned some significantly enriched pathway, which is very surprising.

**Comment by zqfang** [comment]
The prerank expected a pre-sorted values (descending order) and gene order matters !   Same values input won't be a problem. e.g you could set weight_score_type to 0, and every value becomes to 1  (value^0). 

You could input a pd.Series or a dataframe with only two column.
