### ISSUE TITLE
Why I can't draw dotplot with prerank example?

### ISSUE THREAD

**Issue by MugenQin** [zqfang/GSEApy#159]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import gseapy; print(gseapy.__version__)
```

(*Please copy and run the above in your Python, and copy-and-paste the output*)

### Expected behaviour

(*Please fill this in*)

### Actual behaviour

(*Please fill this in, and provide any exception message in full*)

### Steps to reproduce

(*Please fill this in*)

**Comment by zqfang** [comment]
Set outdir to some directory you like, not None

**Comment by MugenQin** [comment]
> Set outdir to some directory you like, not None

hi,
Thanks for your reply. I have another question now. I wanna know how can I change the min&max limitation of the legend "Comined Score"?

**Comment by zqfang** [comment]
You have to refer to seaborn/matplotlib, do your own dotplot then.

**Comment by zqfang** [comment]
Now,  dotplot support prerank results , see #165
