### ISSUE TITLE
Why is it possible for a p=0 term to have q=1?

### ISSUE THREAD

**Issue by searchlie** [zqfang/GSEApy#162]
Hi, zqfang.
I recently learned of your GSEApy and immediately tried prerank with [the data I had on hand](https://github.com/searchlie/misc/blob/main/2022-08-16-test.rnk) and compared it to results of the GSEA  provided by Broad institute.
Basically, I was very pleased with the results, as NES, p-value, FWER, etc. appeared to be roughly similar for both.
However, upon closer inspection of the results, I noticed that only FDR (q value ) behaved strangely:

![image](https://user-images.githubusercontent.com/28975498/184860148-5ee86409-f6e3-4eef-916e-7f99ca6ccf08.png)

A striking example is a term with p=0 that has q=1 (left). This term had p=0 and q=0 in Broad's GSEA (right):

![image](https://user-images.githubusercontent.com/28975498/184861349-08e9b7de-f9b2-4dec-bbe1-0abd8e67d7e2.png)

To investigate the issue in depth, I plotted the p and q values and discovered that the relationship can be V-shaped in GSEApy (left), but is roughly monotonic in Broad's results (right). 

![image](https://user-images.githubusercontent.com/28975498/184861754-8e946664-ee49-467a-aaea-ec84381baec5.png)

Is this a bug? If it is the intended specification, could you please tell me what could cause such a difference?

### Setup

GSEApy version: 0.11.0
Python version: 3.9.6
OS: Debian 11.4

[Used rnk file](https://github.com/searchlie/misc/blob/main/2022-08-16-test.rnk)

Used option:
```python
pre_res = gp.prerank(rnk=rnk, gene_sets="c2.cp.kegg.v7.5.1.symbols.gmt", min_size=5)
```

**Comment by zqfang** [comment]
Thanks for the comparasion !  I think it's a bug in the recent updated rust code. I will get back to you soon

**Comment by zqfang** [comment]
Now, it's fixed. see a new release (v0.12.1) for this critial bug fixed

**Comment by searchlie** [comment]
Thank you for your prompt response!
I updated gseapy and now confirmed that the p=0 term has a properly low q value.
For reference, I have included some new figures below.

![image](https://user-images.githubusercontent.com/28975498/184999542-088a1385-cc09-40e6-9102-0a3c58d367ae.png)

When comparing to Broad's GSEA, it still does not ride on the diagonal completely, but it does ride on the lower q-values, so it looks good for practical use.
Very much appreciated!!!

**Comment by zqfang** [comment]
Thank you very much for the feeback. it really helps. So other's could have a reference here.

there are  two reason have you don't align well:

(1) I used an approximate method to speed up the calcualtion of [FDR q](https://github.com/zqfang/GSEApy/blob/277854048e26c9275ad285530a57d4799c7d597b/src/stats.rs#L277). which is  not exactly the same implement as GSEA_R [here](https://github.com/zqfang/GSEApy/blob/277854048e26c9275ad285530a57d4799c7d597b/src/stats.rs#L231) 

(2) the permutation procedure is hard to make the comparsion fail between GSEA-P and GSEApy.

But anyway, it won't too much, since we focuse top signicantly changed pathway most of the time.

**Comment by zqfang** [comment]
Hi @searchlie, unfortunately, I found another critial bug when calculating FDR values in Rust code. and Now is fixed. Please update to 0.13.0 as soon as possible.
```shell
pip install -U gseapy
```

**Comment by searchlie** [comment]
Hi @zqfang. Thanks for the update!
I immediately used v0.13.0 and compared its q value with the q value output by the Broad instiitute software.
It seems to correlate definitely better than v0.12.0!
I appreciate your fantastic job!
![image](https://user-images.githubusercontent.com/28975498/188263992-404c47e0-0b39-42a7-bc64-3855b9fd58ee.png)

**Comment by zqfang** [comment]
Thanks for the comparsion, too. Yeah. It's my bad. I should notice the weird thing more earlier. I thought the previously result was caused by the approximate method I've implememented. It turns out that It was a mistake I've made a when converting numpy to Rust code.

**Comment by searchlie** [comment]
@zqfang 
This is not a bug report, but a report about a hidden change I noticed recently.
In previous versions, the results (res2d) were sorted by ES or NES value, but in the latest version, they seemed to be sorted by FWER p-val value.
Is my understanding correct?
(I would like to check the code directly, but I can't read the Rust code...sorry.)

**Comment by zqfang** [comment]
in the previous version, the final output results are sorted by FDR. Now are sorted by the absolute value of NES, which will make the sorting order more deterministic. 

The sorting only affects the row orders in the output table.  You could sort the table whatever you like.

**Comment by searchlie** [comment]
Very well understood, thank you!
