### ISSUE TITLE
KeyError: 'Adjusted P-value' in dotplot

### ISSUE THREAD

**Issue by alexlenail** [zqfang/GSEApy#165]
from the [docs](https://gseapy.readthedocs.io/en/latest/gseapy_example.html?highlight=mouse#Mouse-gene-symbols-maps-to-Human,-or-vice-versa)

```
from gseapy import barplot, dotplot

dotplot(res.res2d, title='WikiPathways_2019_Mouse', cmap='viridis_r', size=20, figsize=(3,5))
```
throws error: 
```
KeyError: 'Adjusted P-value'
```

the columsn of res2d are
```
 Index(['Name', 'Term', 'ES', 'NES', 'NOM p-val', 'FDR q-val', 'FWER p-val',
       'Tag %', 'Gene %', 'Lead_genes'],
```

**Comment by zqfang** [comment]
dotplot is not designed for GSEA results initially.

However, if you install gseapy from the lastest push, you could do this 

```
from gseapy import dotplot
# to save your figure, make sure that ``ofname`` is not None
ax = dotplot(pre_res.res2d, 
             column="FDR q-val",
             title='KEGG_2016',
             cmap=plt.cm.viridis, 
             size=8, # adjust dot size
             figsize=(4,5), cutoff=0.25)
```

![image](https://user-images.githubusercontent.com/5889336/190492693-1df8e444-4d0c-4fbd-a814-4173b886e887.png)
