### ISSUE TITLE
install error on Google Colab

### ISSUE THREAD

**Issue by samuelpayne** [zqfang/GSEApy#166]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

Using Google Colab, I am trying to install gseapy with the following commands
!python --version
> Python 3.7.14

!pip install gseapy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting gseapy
  Downloading gseapy-0.13.0.tar.gz (1.5 MB)
     |████████████████████████████████| 1.5 MB 35.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from gseapy) (3.2.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from gseapy) (1.3.5)
Collecting bioservices
  Downloading bioservices-1.10.1.tar.gz (964 kB)
     |████████████████████████████████| 964 kB 72.8 MB/s 
Requirement already satisfied: numpy>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from gseapy) (1.21.6)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from gseapy) (2.23.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from gseapy) (1.7.3)
Collecting grequests
  Downloading grequests-0.6.0-py3-none-any.whl (5.2 kB)
Collecting requests_cache
  Downloading requests_cache-0.9.6-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 5.6 MB/s 
Collecting easydev>=0.9.36
  Downloading easydev-0.12.0.tar.gz (47 kB)
     |████████████████████████████████| 47 kB 5.0 MB/s 
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bioservices->gseapy) (4.6.3)
Collecting xmltodict
  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from bioservices->gseapy) (4.9.1)
Collecting suds-community
  Downloading suds_community-1.1.2-py3-none-any.whl (144 kB)
     |████████████████████████████████| 144 kB 74.3 MB/s 
Requirement already satisfied: appdirs in /usr/local/lib/python3.7/dist-packages (from bioservices->gseapy) (1.4.4)
Requirement already satisfied: wrapt in /usr/local/lib/python3.7/dist-packages (from bioservices->gseapy) (1.14.1)
Collecting colorlog
  Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Collecting colorama
  Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from easydev>=0.9.36->bioservices->gseapy) (4.8.0)
Collecting gevent
  Downloading gevent-21.12.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (5.8 MB)
     |████████████████████████████████| 5.8 MB 59.5 MB/s 
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from gevent->grequests->bioservices->gseapy) (57.4.0)
Requirement already satisfied: greenlet<2.0,>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from gevent->grequests->bioservices->gseapy) (1.1.3)
Collecting zope.event
  Downloading zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
Collecting zope.interface
  Downloading zope.interface-5.4.0-cp37-cp37m-manylinux2010_x86_64.whl (251 kB)
     |████████████████████████████████| 251 kB 73.9 MB/s 
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->gseapy) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->gseapy) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->gseapy) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->gseapy) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib->gseapy) (4.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib->gseapy) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->gseapy) (2022.2.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->easydev>=0.9.36->bioservices->gseapy) (0.7.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->gseapy) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->gseapy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->gseapy) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->gseapy) (2.10)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 54.3 MB/s 
Collecting cattrs>=1.8
  Downloading cattrs-22.1.0-py3-none-any.whl (33 kB)
Collecting url-normalize>=1.4
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.7/dist-packages (from requests_cache->bioservices->gseapy) (22.1.0)
Collecting exceptiongroup
  Downloading exceptiongroup-1.0.0rc9-py3-none-any.whl (12 kB)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/setuptools-57.4.0.dist-info/METADATA'

### Expected behaviour

This used to work. I think I last tried it was this summer and there was no errors

### Actual behaviour

see error dump above

### Steps to reproduce

open colab and do the two commands
!python --version
!pip install gseapy

**Comment by samuelpayne** [comment]
I think it might be solved by trying an older version of gseapy
!pip install gseapy==0.10.7

but I am still checking things out

**Comment by zqfang** [comment]
I've uploaded a pre-compiled gseapy to pypi. You simple need to re-run the pip now.

I would recommend use gseapy >= 0.13.0. It runs faster and required much less memory 

<img width="588" alt="image" src="https://user-images.githubusercontent.com/5889336/193100824-185fd980-3976-49a3-b7ca-52ade7c8bdcc.png">

**Comment by samuelpayne** [comment]
THanks
