### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by HelloWorldLTY** [zqfang/GSEApy#168]
I meet this error when I intend to run GSEA on my python. Could you please suggest me some solutions? Thanks a lot.

**Comment by HelloWorldLTY** [comment]
After I used my own computer to run the codes, I meet a new error:
![image](https://user-images.githubusercontent.com/43333475/195964264-dcdb127c-3168-4045-932c-6cf8724d4fb8.png)

I wonder if there are any solutions to this problem. Thanks a lot.

**Comment by zqfang** [comment]
See also #167 

how did you install gseapy ?

**Comment by HelloWorldLTY** [comment]
I used pip install. Maybe I need to try conda

**Comment by zqfang** [comment]
Yeah. or you could install gseapy from source. 

and rust too.

```shell
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by wdg118** [comment]
> Yeah. or you could install gseapy from source.
> 
> and rust too.
> 
> ```shell
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> ```

I tried this as tried to import gseapy again and this also did not work.

**Comment by zqfang** [comment]
That's weird. What's the error message? @wdg118 

What platform you are using ?

you might try to use the  command here to force  install the latest binaries, not the cache one
```shell
pip install gseapy --force
```

**Comment by zqfang** [comment]
The newest release has pre-compiled binaries for most platforms. close now
