### ISSUE TITLE
Missing plots after running GSEA

### ISSUE THREAD

**Issue by AnzeLovse** [zqfang/GSEApy#169]
Thank you for providing a Python implementation of GSEA. With the latest GSEApy version some plots are missing in the output.

### Expected behaviour

The specified number (`graph_num`) of plots is saved to disk when running `gseapy.gsea()` function.

### Actual behaviour

Updating from 0.10.7 to 0.14.0 resulted in missing heat maps and GSEA plots. For example, running the script below with 20 genes saves two plots for geneset `foo`. Running the same script with 1000 genes results in no output figures. When using 20 genes, `foo` has p < 0.05, whereas it is 1.0 with 1000 genes. Did 0.14.0 introduce any filtering before outputting the plots?
### Steps to reproduce

Run the script below with 20 and 1000 `N_GENES`.
There are no plots in the demo_run_1000 directory and no `gsea` directory is created.

```
import gseapy

import numpy as np
import pandas as pd


N_GENES = 20

rng = np.random.default_rng(seed=42)
exp = rng.uniform(low=0.0, high=100.0, size=(6, N_GENES))
expressions = pd.DataFrame(
    exp,
    index=[f"SAMPLE_{i}" for i in range(6)],
    columns=[f"GENE_{i}" for i in range(N_GENES)],
)

gene_set = {"foo": [f"GENE_{i}" for i in range(15)]}
classes = [
    "case",
    "case",
    "case",
    "control",
    "control",
    "control",
]

gsea_output = gseapy.gsea(
    data=expressions.T,
    gene_sets=gene_set,
    cls=classes,
    outdir=f"demo_run_{N_GENES}",
    permutation_num=100,
    seed=42,
    graph_num=20,
    no_plot=False,
    verbose=True,
)
print(gsea_output.res2d)
```

System info:
```
3.8.2 (default, Apr  7 2020, 11:53:08) 
[Clang 11.0.3 (clang-1103.0.32.29)]
CPython
macOS-10.16-x86_64-i386-64bit
gseapy-0.14.0
```

**Comment by zqfang** [comment]
Hi @AnzeLovse , The current version of gseapy will reduce the output figure number by FDR < 0.25 by default. In other words, the plot will not be generated when FDR > 0.25 no matter how many figure numbers you've set. refer to [here](https://github.com/zqfang/GSEApy/blob/90961cb638d88c8da277ba942e77a90443917f9e/gseapy/base.py#L305) 


However, you could generate the plot manually in python console, since you could access all the data to re-produce figure

e.g.
```python
from gseapy import gseaplot

# pick a term you need
terms = gsea_output.res2d.Term
i = 2
# Make sure that ``ofname`` is not None, if you want to save your figure to disk
gseaplot(gs_res.ranking, term=terms[i], **gsea_output.results[terms[i]])

```

**Comment by AnzeLovse** [comment]
Thank you for your prompt response. It seems appropriate to filter out truly non-significant results although the old functionality offered a bit more control. Manual plotting will also work fine.
