### ISSUE TITLE
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None`

### ISSUE THREAD

**Issue by kanekalla** [zqfang/GSEApy#170]
### Setup

Hi there,
I am having an issue running GSEApy. Can anyone look into this. I think its a rust specific issue ?
Please find the other info and the error below.

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import gseapy; print(gseapy.__version__)
```

>>> import sys; print(sys.version)
3.9.13 (main, May 23 2022, 22:01:06)
[GCC 9.4.0]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-5.4.0-107-generic-x86_64-with-glibc2.31
>>> import gseapy; print(gseapy.__version__)
0.14.0
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-date: 2022-09-19
host: x86_64-unknown-linux-gnu
release: 1.64.0
LLVM version: 14.0.6

### Actual behaviour

File "/home/gsea_tasks.py", line 51, in run_gsea_for_hallmark_pathways
    pre_res = gsea.prerank(rnk=deg_rank_file, gene_sets='MSigDB_Hallmark_2020',
  File "/containerhome/.local/lib/python3.9/site-packages/gseapy/__init__.py", line 359, in prerank
    pre.run()
  File "/containerhome/.local/lib/python3.9/site-packages/gseapy/gsea.py", line 380, in run
    gsum = prerank_rs(
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value

**Comment by zqfang** [comment]
Could you share your `deg_rank_file` to reproduce the bug ?

**Comment by kanekalla** [comment]
[test_rankfile.csv](https://github.com/zqfang/GSEApy/files/9895890/test_rankfile.csv)
Thank you @zqfang !

**Comment by zqfang** [comment]
Hi @kanekalla,

Your input rnk contains `inf` values. You need to take care of these `inf` values

<img width="679" alt="image" src="https://user-images.githubusercontent.com/5889336/198895764-3d5ab0b0-d5a3-4330-8ee8-0a2f51df7346.png">

**Comment by kanekalla** [comment]
Thanks @zqfang , I missed that, confused with NaNs.

**Comment by zqfang** [comment]
@kanekalla , thanks for reporting the bug. The inf issue will be addressed in the next release

**Comment by zqfang** [comment]
The newest release fixed the issue
