### ISSUE TITLE
unable to get ax when calling barplot()

### ISSUE THREAD

**Issue by nathaliehsieh** [zqfang/GSEApy#171]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

```python
3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:21:18) 
[GCC 9.3.0]
CPython
Linux-4.15.0-169-generic-x86_64-with-glibc2.10
0.14.0
```

### Expected behaviour
get `ax` when calling` barplot()` without setting 'ofname' to visualize the enrichr results.

### Actual behaviour
When I run `ax = barplot(enr.res2d) `, I got 'NoneType' object returned.

```python
import gseapy as gp
from gseapy.plot import barplot

enr = gp.enrichr(gene_list=gene_list, # or "./tests/data/gene_list.txt",
                 gene_sets=['KEGG_2016','KEGG_2021_Human'],
                 organism='human', # don't forget to set organism to the one you desired! e.g. Yeast
                 outdir=None, # don't write to disk
                )
ax = barplot(enr.res2d,title='KEGG_2021_Human', figsize=(3, 5))
print(type(ax))
```

output

<img width="600" alt="image" src="https://user-images.githubusercontent.com/87373437/198982385-986d8c71-5055-4286-b43c-c922de32b42a.png">

### Steps to reproduce

-----
Thank you!

**Comment by zqfang** [comment]
Hi @nathaliehsieh,

Thanks for reporting the bug. The quickest way to get the ax it to delete line 879-880 of code in below:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/5889336/199069617-255a0cdd-9da2-46ee-81c6-88840b5704b1.png">

**Comment by zqfang** [comment]
The newest release fixed this issue.
