### ISSUE TITLE
Data storage is unstable

### ISSUE THREAD

**Issue by thomasgaudelet** [zqfang/GSEApy#174]
I am reporting a problem with GSEApy (independent of version, etc.)
It seems the data from mayaan.cloud/ is not (always) accessible, which is confirmed when trying to access any page or download via a browser (Error 502, bad gateway).

e.g. https://maayanlab.cloud/Enrichr/datasetStatistics 

Note that we had a ~15mins window during which it worked fine, but it seems down again at time of writing.
Specifically, error we are seeing is the following when using the package
```
        lib_url = self.ENRICHR_URL + "/Enrichr/datasetStatistics"
        response = requests.get(lib_url, verify=True)
        if not response.ok:
>           raise Exception("Error getting the Enrichr libraries")
E           Exception: Error getting the Enrichr libraries
```

**Comment by zqfang** [comment]
I don't have a good solution for this. The Enrichr server will block the query sometimes. 

You have to re-try if the query was failed though.

**Comment by zqfang** [comment]
I've added a retry strategy to relieve the failure in the v1.0.3. , If Enrichr server keep rejecting requests, I could do nothing

**Comment by kokyriakidis** [comment]
Dear @zqfang 

The "Error getting the Enrichr libraries" is not resolved. Are you sure you are using the correct links for the databases?
