### ISSUE TITLE
error with dotplot()

### ISSUE THREAD

**Issue by nargesr** [zqfang/GSEApy#175]
Hi,

after updating GSEApy to version 1.0.0, I got this error when I try to use `dotplot()`:

`
~/opt/anaconda3/lib/python3.9/site-packages/gseapy/plot.py in dotplot(df, column, title, cutoff, top_term, size, figsize, cmap, ofname, **kwargs)
    504     # get scatter area
    505     ol = df.columns[df.columns.isin(["Overlap", "Tag %"])]
--> 506     temp = df[ol].squeeze().str.split("/", expand=True).astype(int)
    507     df = df.assign(Hits_ratio=temp.iloc[:, 0] / temp.iloc[:, 1])
    508     # make area bigger to better visualization

AttributeError: 'str' object has no attribute 'str'
`

**Comment by zqfang** [comment]
how many rows do your input dataframe has ?

**Comment by nargesr** [comment]
I do have 4320 rows

**Comment by zqfang** [comment]
could you show me your dataframe's header ?

**Comment by nargesr** [comment]
there are 10 columns including ['Gene_set', 'Term', 'Overlap', 'P-value', 'Adjusted P-value', 'Old P-value', 'Old Adjusted P-value', 'Odds Ratio', 'Combined Score', 'Genes']

![image](https://user-images.githubusercontent.com/57965133/204933734-ab6af3a9-b157-4d55-96d9-305d707e5de1.png)

**Comment by zqfang** [comment]
sorry. I can't reproduce the issue you have. Would you please send you dataframe file to me? I could checkout it out

**Comment by zqfang** [comment]
Hi @nargesr, 

By default, dotplot will show column='Adjusted P-value', with cutoff<=0.05. In your dataframe, there's only 1 enriched term left.

You could use 
```
dotplot(df, column='P-value')
```
to avoid the bug for now

**Comment by zqfang** [comment]
New release v1.0.1 take good care of this minor issue.
