### ISSUE TITLE
gseapy.gsea() is it bug? 

### ISSUE THREAD

**Issue by kirillkrs** [zqfang/GSEApy#178]
## **Hi!**

I have some problems with gseapy.gsea() class like this:

>  _/Users/cytoscape/opt/anaconda3/envs/bioinf/lib/python3.10/site-packages/gseapy/gsea.py:110: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function._
df_std = df.groupby(by=cls_dict, axis=1).std()

--------------- AND ---------------

> _/Users/cytoscape/opt/anaconda3/envs/bioinf/lib/python3.10/site-packages/gseapy/gsea.py:168: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function._
df_std = df.groupby(by=classes, axis=1).std()

If I understood right it's error in 110 and 168 line in gsea.py file. But I can't understand were is wrong.

Error lines in gsea.py file.

**110 line:**
![110_error_line](https://user-images.githubusercontent.com/93524208/205067936-5513a628-9c58-40c0-a525-674c9e581b05.png)

**168 line:**
![168_error_line](https://user-images.githubusercontent.com/93524208/205067967-9a8bda65-b91f-4a7b-8909-23a8148f1cbe.png)

---------------------

My code:
`kegg_gs_res = gp.gsea(data=hdc_genes, gene_sets='KEGG_2021_Human', cls=class_vector, permutation_type='gene_set',                      
                                          permutation_num=1000, outdir='../gseapy/gp_gsea_res/kegg_res', method='log2_ratio_of_classes', 
                                          threads=4, seed=7, ascending=True)`

---------------------

I've tried using different count matrix data with gene names like index and column of pandas df. I did my code from gseapy example on readthedocs: **_[click](https://gseapy.readthedocs.io/en/latest/gseapy_example.html#4.-GSEA-Example:~:text=gmt%20%2Do%20prerank_report_temp-,4.%20GSEA%20Example,-4.1%20Inputs)_**

**My input data matrix is:**
![Data_matrix](https://user-images.githubusercontent.com/93524208/205064117-4dc8a06e-a1d2-4d87-9906-6780b0d19e01.png)

**I also tried use input data matrix like this:**
![Data_matrix1](https://user-images.githubusercontent.com/93524208/205064571-e5d736a4-ca99-4e84-849e-08a015f7da0e.png)
---------------------
Also I used different type of cls [click](https://gseapy.readthedocs.io/en/latest/run.html#gseapy.gsea:~:text=cls%20%E2%80%93%20A%20list%20or%20a%20.cls%20file%20format%20required%20for%20GSEA)  input.
I used cls from class_vector, like this, created from cls file:
![Cls_gseapy](https://user-images.githubusercontent.com/93524208/205065499-200f459e-e920-40f0-8fbe-2eff269897e2.png)

And I used cls from created cls file, from GSEA user guid [click](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/Data_formats), that work in desktop java app:
![Cls_file](https://user-images.githubusercontent.com/93524208/205066012-1d64b75c-b9dc-4b8c-b6c2-ad6671ea62c2.png)

This error appears when I using different databases of gene sets: GO, KEGG, Hallmark, Reactome...

- I am using MacOS version 10.15.7
- Python version 3.10.6
- gseapy version 0.14.0
- Jupyter lab version 3.5.0
- In Anaconda 22.9.0

I hope You could help me solving this issue.

     ================================================
                                                           
          Thank you for your work!!       
     ================================================                                
________________

**Comment by zqfang** [comment]
Hi, this is a warning from pandas. 

I think updating gseapy to 1.0.0 would suppress the warning.  or downgrade your pandas version (<=v1.3)

**Comment by kirillkrs** [comment]
Oh, God. I didn't see that I had wrong version.... 😅 😐 
Now it's work
