### ISSUE TITLE
Broken link in SingleSampleGSEA normalization documentation

### ISSUE THREAD

**Issue by JacobBumgarner** [zqfang/GSEApy#186]
The link provided in the `norm_sample(...)` function of the `SingleSampleGSEA` class is broken.

Broken link in question for ease of reference:
http://rowley.mit.edu/caw_web/ssGSEAProjection/ssGSEAProjection.Library.R

Perhaps instead it could be replaced by the source code hosted by @olgabot under the following link:
https://github.com/olgabot/rna-seq-diff-exprn/blob/e36a3bc668c3645ca156525cfec70152bd68f9fb/scripts/expression/ssGSEA/ssGSEAProjection/ssGSEAProjection.Library.R#L93

Minor suggestion!

**Comment by zqfang** [comment]
updated. close now
