### ISSUE TITLE
New anaconda package install broken

### ISSUE THREAD

**Issue by nwieder** [zqfang/GSEApy#191]
### Setup

I am reporting a problem with gseapy-0.12.0 from the bioconda repo (python 3.9)
system as follows:

```python
import gseapy
```

### Expected behaviour

Load gseapy package

### Actual behaviour

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 18
     15 from scipy.stats import ttest_ind as ttst
     17 from dynamicTreeCut.dynamicTreeCut import cutreeHybrid
---> 18 import gseapy
     19 # import biomartpy.core as bmp
     21 from sklearn.decomposition import PCA

File ~/miniconda3/envs/bio/lib/python3.9/site-packages/gseapy/__init__.py:9
      7 from .biomart import Biomart
      8 from .enrichr import Enrichr
----> 9 from .gsea import GSEA, Prerank, Replot, SingleSampleGSEA
     10 from .parser import get_library_name
     11 from .plot import barplot, dotplot, gseaplot, heatmap

File ~/miniconda3/envs/bio/lib/python3.9/site-packages/gseapy/gsea.py:15
     12 import pandas as pd
     14 from gseapy.base import GSEAbase
---> 15 from gseapy.gse import Metric, gsea_rs, prerank_rs, ssgsea_rs  # import gseapy rust lib
     16 from gseapy.parser import gsea_cls_parser
     17 from gseapy.plot import gseaplot

ModuleNotFoundError: No module named 'gseapy.gse'
```

### Steps to reproduce

Install latest version of gseapy from bioconda and load package.

**Comment by zqfang** [comment]
CAre you using widows? If yes, you need to use pip

pip install gseapy

**Comment by nwieder** [comment]
Thanks for the quick response. I am using Mac 13.2 and python 3.9
I tried to install with pip (also in a fresh env) and I receive the same error

Interestingly, if I create a vanilla python 3.11 env and install gseapy with pip it works. Conda install doesn't work with 3.11 either.

**Comment by zqfang** [comment]
I think bioconda did not have the pre-build package for your hardware (like M1)

**Comment by nwieder** [comment]
I see, I just switched to the M1 Mac. Maybe stupid question, but is it straight forward to build the latest gseapy? Do you how and when a compiled M1 version will be available in bioconda?
For now I can just use the previous version which works fine.

**Comment by zqfang** [comment]
bioconda only provides 64-bit MacOS package. Note sure when M1 will be supported. You could build you own with conda, but I think the easiest way is to install via pip

I recommend using the lastest version, which provides much faster speed and more features.

**Comment by nwieder** [comment]
Alright - sorry for closing this only now. I installed everything into a fresh environment and gseapy from pip works in python 3.9. now. 

Thanks for your insights!

**Comment by BeyondTheProof** [comment]
For future readers: I'm getting the same error on a different OS and different python version.

I ran `mamba install -c conda-forge -c bioconda gseapy`, and running `import gseapy as gp` in python 3.11 on a Unix x86_64 system yields the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[497], line 1
----> 1 import gseapy as gp

File ~/env/mambaforge/envs/rome/lib/python3.11/site-packages/gseapy/__init__.py:9
      7 from .biomart import Biomart
      8 from .enrichr import Enrichr
----> 9 from .gsea import GSEA, Prerank, Replot, SingleSampleGSEA
     10 from .parser import get_library_name
     11 from .plot import barplot, dotplot, gseaplot, heatmap

File ~/env/mambaforge/envs/rome/lib/python3.11/site-packages/gseapy/gsea.py:15
     12 import pandas as pd
     14 from gseapy.base import GSEAbase
---> 15 from gseapy.gse import Metric, gsea_rs, prerank_rs, ssgsea_rs  # import gseapy rust lib
     16 from gseapy.parser import gsea_cls_parser
     17 from gseapy.plot import gseaplot

ModuleNotFoundError: No module named 'gseapy.gse'
```

I tried following the suggestion [in issue 161](https://github.com/zqfang/GSEApy/issues/161) by installing rust with conda, then gseapy with pip. I got the same error.

I thought it was maybe still was using the mamba installation, so I uninstalled gseapy from the Mamba env, and installed with only pip, and restarted my kernel. This resolved the problem!

Regardless, I think something is wrong with the conda package, so it would be good investigating. Good hunting!
