### ISSUE TITLE
Over-representation analysis via Enrichr web services error with large gene lists

### ISSUE THREAD

**Issue by Kev5nJC** [zqfang/GSEApy#192]
Hi,

I'm experiencing an issue with the over representation analysis via Enrichr webservices functionality of GSEApy.  Currently I have multiple gene lists which I would like to characterize.  I am currently utilizing all three GO_2021 libraries for comparison.  I have had no issues when running my first (n=23) and second (n=12,129) gene lists.  However, when I run my third gene list (n=25,115), I receive the following error:

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11972\2671021840.py in <module>
      1 # run enrichr
      2 # if you are only intrested in dataframe that enrichr returned, please set outdir=None
----> 3 enr = gp.enrichr(
      4         gene_list = glist, # or "./tests/data/gene_list.txt",
      5         gene_sets = gene_sets,

~\anaconda3\lib\site-packages\gseapy\__init__.py in enrichr(gene_list, gene_sets, organism, outdir, background, cutoff, format, figsize, top_term, no_plot, verbose)
    507     # set organism
    508     enr.set_organism()
--> 509     enr.run()
    510 
    511     return enr

~\anaconda3\lib\site-packages\gseapy\enrichr.py in run(self)
    502                 self._logger.debug("Enrichr service using library: %s" % (self._gs))
    503                 # self._logger.info("Enrichr Library: %s"% self._gs)
--> 504                 shortID, res = self.get_results(genes_list)
    505                 # Remember gene set library used
    506             res.insert(0, "Gene_set", self._gs)

~\anaconda3\lib\site-packages\gseapy\enrichr.py in get_results(self, gene_list)
    226         """Enrichr API"""
    227         ADDLIST_URL = "%s/%s/addList" % (self.ENRICHR_URL, self._organism)
--> 228         job_id = self.send_genes(gene_list, ADDLIST_URL)
    229         user_list_id = job_id["userListId"]
    230 

~\anaconda3\lib\site-packages\gseapy\enrichr.py in send_genes(self, gene_list, url)
    201         response = requests.post(url, files=payload, verify=True)
    202         if not response.ok:
--> 203             raise Exception("Error sending gene list, try again later")
    204         job_id = json.loads(response.text)
    205 

**Exception: Error sending gene list, try again later**
```

Is this an issue due to the large gene list size?  Is the request too large for Enrichr webservices?  Is there anyway to fix or bypass this?  Or should I consider running the analysis differently with PreRanked GSEA?

Thank you so much for this tool, your work is greatly appreciated.

Cheers!

**Comment by zqfang** [comment]
I think your gene list is too large ( >20K ) for over-representation analysis.

try to prioritize your gene list, or 

1. download GMT file, eg.
```
## download a library or read a .gmt file
go_mf = gp.get_library(name='GO_Molecular_Function_2018')
print(go_mf['ATP binding (GO:0005524)'])
```
2. run offline mode (without combined score output)
```
# NOTE: `enrich` instead of `enrichr`
enr2 = gp.enrich(gene_list= [...],
                 gene_sets= go_mf,
                 background=None, # you could set a background, e.g. "hsapiens_gene_ensembl",
                 ）
···

3. or try prerank 

```

**Comment by Kev5nJC** [comment]
Downloading the libraries and running offline mode worked perfectly!  In fact, it was much more efficient than running the webservice.  It's a shame that large gene sets cannot be run via the web services, but the solution to this problem works way better.

Thank you for the quick reply & help.  It is greatly appreciated.

Keep up the good work.
