### ISSUE TITLE
Matplotlib support failed

### ISSUE THREAD

**Issue by Skychou-source** [zqfang/GSEApy#200]
When I execute the following code, an error occurs:
import gseapy as gp from gseapy import barplot
**The error message is as follows:**
Matplotlib support failed
TypeError: vars() argument must have dict attribute
Strangely, there was no error when I imported it again and it can be used normally.
Although this does not affect normal use, it may cause problems if I want to use it in my code.

**The versions of various packages are as follows:**
gseapy==1.0.4
matplotlib==3.7.0
pandas==1.5.3
requests==2.23.0
numpy >= 1.13.0

**Comment by zqfang** [comment]
did you run your code in jupyter or in other consoles? 

if you cannot reproduce the error repeatedly, I can't fix it

**Comment by Skychou-source** [comment]
I am running the code in PyCharm environment and not in any other console.
I fixed this issue. Use the code below:
```
import matplotlib
matplotlib.use('Agg')
```
thanks : )
