### ISSUE TITLE
Zeros in GSEA result

### ISSUE THREAD

**Issue by hfl112** [zqfang/GSEApy#201]
Hi developers,
I just got my GSEA result, but have hundreds of the pathways showing both pval and fdr = 0. In my result, the smallest values except zero is 0.00001, so is it possible to make it to scientific numbers instead of numeric float?

What does 0 in these result means?

**Comment by zqfang** [comment]
see [here](https://gseapy.readthedocs.io/en/latest/faq.html#q-why-p-value-or-fdr-is-0-not-a-very-small-number)
