### ISSUE TITLE
How to preserve mouse specific genes when downloading it from get_library()

### ISSUE THREAD

**Issue by Smilenone** [zqfang/GSEApy#204]
Hi, I am going to use KEGG_2019_Mouse to study mouse related pathways, where I used code:
`KEGG_mouse = gp.get_library(name='KEGG_2019_Mouse', organism='mouse')`
However, the downloaded genes are Human genes symbols, I had to to use bm.query() in your toturial to convert them to Mouse. In this process, 0~1096 genes in different pathways are dropped. Making a result that in each pathways, the converted version has less genes than the origin one. Does this a true result,  or a bad phenomenon because of the ID convertion? Can I download the KEGG_2019_Mouse in the mouse gene symbols directly?

**Comment by zqfang** [comment]
You can download the gmt file directly from here: https://maayanlab.cloud/Enrichr/#libraries

Unfortunately, enrichr website use the same gmts for both human and mouse (all upcases)

**Comment by Smilenone** [comment]
Thanks for your timely response!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zqfang/GSEApy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月20日(星期六) 上午7:11
***@***.***&gt;;
抄送:&nbsp;"Qunlun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zqfang/GSEApy] How to preserve mouse specific genes when downloading it from get_library() (Issue #204)





 
You can download the gmt file directly from here: https://maayanlab.cloud/Enrichr/#libraries
 
Unfortunately, enrichr website use the same gmts for both human and mouse (all upcases)

**Comment by zqfang** [comment]
v1.0.6 now have the MSIGDB api to download mouse GMT file with gene symbol/entrezid directory. close now
