### ISSUE TITLE
Confusion regarding the positive and negative phenotype specification in gsea objects

### ISSUE THREAD

**Issue by chrissymkcn** [zqfang/GSEApy#211]
### Setup

I am reporting a problem with GSEApy version '1.0.4', Python 3.9.16, and on linux Centos. It started with when I checked the .pheno_pos and .pheno_neg attributes of the returned gsea object and found that it was in fact the opposite as what I specify during input by the 'pos' and 'neg' parameter. As I checked the implementation, in the [load_classes](https://github.com/zqfang/GSEApy/blob/master/gseapy/gsea.py#L277) function if the input class is not a dictionary, the self.pheno_pos and self.pheno_neg are assigned the first and second unique value, and so are not the ones specified during the gsea function call. Could you check if this is true and if so please try to fix it, as it would result in opposite results completely.

**Comment by zqfang** [comment]
Yes. self.pheno_pos and self.pheno_neg are assigned the first and second unique value. 

I don't think there's no option that you could explicitly assign pos and neg manually for `gsea` currently. 

You can change the order of your input classes and it's data. or just use prerank statistics

**Comment by zqfang** [comment]
Finally,  we can set pheno_pos and pheno_neg mannually

```python
from gseapy import GSEA
from gseapy import GSEA
gs = GSEA(data="./tests/extdata/Leukemia_hgu95av2.trim.txt",
                 gene_sets='KEGG_2016',
                 classes = "./tests/extdata/Leukemia.cls"
)
# set here
gs.pheno_pos = ...
gs.pheno_neg = ...
gs.run()

```
