### ISSUE TITLE
Dotplot annotations

### ISSUE THREAD

**Issue by BelanaZ** [zqfang/GSEApy#212]
### Description
Hi, I experienced some minor issues with the Dotplot. Maybe you have some tips on how I can avoid them or you can improve them in the future:
- The annotation overlaps the legend most of the time, especially when plotting a larger number of terms.
- For FDR q-val as the column value the annotation should say log10(1/qval) and not log10(1/pval)

Thank you!

![image](https://github.com/zqfang/GSEApy/assets/66524915/4c840a7f-7c0c-4724-9afe-b326cb6a165c)

### Code

```
size_y = max((input_df["FDR q-val"] < cutoff).sum(), 5)
        ax = gseapy.dotplot(
            input_df,
            column="FDR q-val",
            x="NES",
            figsize=(5, size_y),
            cutoff=cutoff,
            title=title,
            show_ring=show_ring,
        )
```

### Setup

```
3.11.0 | packaged by conda-forge | (main, Jan 16 2023, 14:12:30) [MSC v.1916 64 bit (AMD64)]
CPython
Windows-10-10.0.22621-SP0
1.0.5
```

**Comment by zqfang** [comment]
fixed in v1.0.6.  close now
