### ISSUE TITLE
Can not import a package after update 

### ISSUE THREAD

**Issue by azbukinanadezda** [zqfang/GSEApy#213]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
CPython
Linux-3.10.0-1160.81.1.el7.x86_64-x86_64-with-glibc2.17
gseapy version 2.17

### Expected behaviour

I installed gseapy using `conda install -c bioconda gseapy`
However when I import it `import gseapy`, I get an error 

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[192], line 1
----> 1 import gseapy

File ~/anaconda3/envs/EDA/lib/python3.11/site-packages/gseapy/__init__.py:9
      7 from .biomart import Biomart
      8 from .enrichr import Enrichr
----> 9 from .gsea import GSEA, Prerank, Replot, SingleSampleGSEA
     10 from .parser import get_library_name
     11 from .plot import barplot, dotplot, gseaplot, heatmap

File ~/anaconda3/envs/EDA/lib/python3.11/site-packages/gseapy/gsea.py:15
     12 import pandas as pd
     14 from gseapy.base import GSEAbase
---> 15 from gseapy.gse import Metric, gsea_rs, prerank_rs, ssgsea_rs  # import gseapy rust lib
     16 from gseapy.parser import gsea_cls_parser
     17 from gseapy.plot import gseaplot

ModuleNotFoundError: No module named 'gseapy.gse'

Could you please help me to resolve this issue?

**Comment by zqfang** [comment]
You have used py3.11, which bioconda did not have py311 build yet. 

Instead, you have to use `pip` for now

```
pip install gseapy
```

**Comment by azbukinanadezda** [comment]
Thank you for the answer @zqfang 
I uninstalled and installed via pip. Now the error is different:
`cannot import name 'enrichment_map' from 'gseapy.plot' (~/anaconda3/envs/EDA/lib/python3.11/site-packages/gseapy/plot.py)`

I also tried to install earlier versions of gseapy (1.0.4 and 1.0.3), error remains the same:(

**Comment by zqfang** [comment]
That's weird. can you try re-start your python interpreter, and import again ?

**Comment by josenimo** [comment]
I restarted VScode, and it worked 👍
