### ISSUE TITLE
ORA (enrichr) by offline doesn't work with Entrez Gene IDs.

### ISSUE THREAD

**Issue by 136s** [zqfang/GSEApy#219]
Hi,

When I attempt to use Entrez Gene IDs for inputs, I encounter the following error.

This modification 136s@e52a7b1c7fd7ca6db4544769517cb4c5863a2e6b seems to work for the following minimal working example.

### Steps to reproduce

`$ python minimal_working_example.py`

```minimal_working_example.py
#!/usr/bin/env python

import subprocess
from gseapy import enrichr

# get gmt file
gmt_url = "https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2023.1.Hs/c2.cp.kegg.v2023.1.Hs.entrez.gmt"
gmt_filename = gmt_url.split("/")[-1]
subprocess.run(["curl", gmt_url, "-o", gmt_filename])

# first gene set (KEGG_N_GLYCAN_BIOSYNTHESIS) of c2.cp.kegg.v2023.1.Hs.entrez.gmt
genelist = [
    "79868", "57171", "6184", "199857", "11253", "10195", "2683", "4249", "6185",
    "3703", "4248", "1603", "4247", "79087", "7991", "57134", "8818", "8813", "23193",
    "56052", "11320", "144245", "201595", "10905", "84920", "440138", "79053", "85365",
    "1798", "91869", "54344", "1650", "11282", "29929", "4122", "4121", "4124", "6480",
    "8703", "29880", "8704", "146664", "79796", "7841", "2530", "4245",
]

# run
print(enrichr(gene_list=genelist, gene_sets=gmt_filename).res2d)
```

### Expected behaviour

| |Gene_set|Term|Overlap|P-value|Adjusted P-value|Odds Ratio|Combined Score|Genes|
|:----|:----|:----|:----|:----|:----|:----|:----|:----|
|0|c2.cp.kegg.v2023.1.Hs.entrez.gmt|KEGG_GALACTOSE_METABOLISM|2/26|0.021404540907508266|0.026755676134385332|11.063175747297011|42.528531249936684|8704;2683|
|1|c2.cp.kegg.v2023.1.Hs.entrez.gmt|KEGG_GLYCOSAMINOGLYCAN_BIOSYNTHESIS_KERATAN_SULFATE|4/15|6.594112017129497e-06|1.648528004282374e-05|35.723339658444026|426.1556298659424|8704;2530;2683;8703|
|2|c2.cp.kegg.v2023.1.Hs.entrez.gmt|KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_LACTO_AND_NEOLACTO_SERIES|3/26|0.0014262087505559746|0.002377014584259958|15.844502277163306|103.82483380017786|8704;2683;8703|
|3|c2.cp.kegg.v2023.1.Hs.entrez.gmt|KEGG_GLYCOSYLPHOSPHATIDYLINOSITOL_GPI_ANCHOR_BIOSYNTHESIS|1/25|0.19810178976233092|0.19810178976233092|6.7478991596638656|10.92467525558147|8818|
|4|c2.cp.kegg.v2023.1.Hs.entrez.gmt|KEGG_N_GLYCAN_BIOSYNTHESIS|46/46|5.2729211676136374e-114|2.6364605838068186e-113|10397.0|2711871.510998971|8704;201595;1798;11282;4245;4247;4248;10905;23193;4249;4122;4124;4121;7841;6184;6185;57134;199857;79796;7991;11320;84920;29880;1603;54344;440138;79053;6480;57171;10195;91869;2530;146664;29929;8813;79087;8818;1650;56052;11253;144245;3703;85365;2683;79868;8703|

[5 rows x 8 columns]

### Actual behaviour

```error.log
Traceback (most recent call last):
  File "C:\Users\136s\Desktop\minimal_working_example.py", line 21, in <module>
    enrichr(gene_list=genelist, gene_sets=gmt_filename)
  File "C:\Users\136s\miniconda3\envs\gseapy\lib\site-packages\gseapy\__init__.py", line 536, in enrichr
    enr.run()
  File "C:\Users\136s\miniconda3\envs\gseapy\lib\site-packages\gseapy\enrichr.py", line 641, in run
    self.results = pd.concat(self.results, ignore_index=True)
  File "C:\Users\136s\miniconda3\envs\gseapy\lib\site-packages\pandas\core\reshape\concat.py", line 372, in concat
    op = _Concatenator(
  File "C:\Users\136s\miniconda3\envs\gseapy\lib\site-packages\pandas\core\reshape\concat.py", line 429, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import gseapy; print(gseapy.__version__)
```

3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)]
CPython
Windows-10-10.0.19045-SP0
1.0.5

### No error example with symbol

```minimal_working_example.py
#!/usr/bin/env python

import subprocess
from gseapy import enrichr

# get gmt file
gmt_url = "https://data.broadinstitute.org/gsea-msigdb/msigdb/release/2023.1.Hs/c2.cp.kegg.v2023.1.Hs.symbols.gmt"
gmt_filename = gmt_url.split("/")[-1]
subprocess.run(["curl", gmt_url, "-o", gmt_filename])

# first gene set (KEGG_N_GLYCAN_BIOSYNTHESIS) of c2.cp.kegg.v2023.1.Hs.symbols.gmt
genelist = [
    "ALG13", "DOLPP1", "RPN1", "ALG14", "MAN1B1", "ALG3", "B4GALT1", "MGAT5", "RPN2",
    "STT3A", "MGAT3", "DAD1", "MGAT2", "ALG12", "TUSC3", "MAN1C1", "DPM2", "DPM1", "GANAB",
    "ALG1", "MGAT4A", "ALG10B", "STT3B", "MAN1A2", "ALG10", "ALG11", "ALG8", "ALG2",
    "DPAGT1", "RFT1", "DPM3", "DDOST", "MGAT4B", "ALG6", "MAN2A2", "MAN1A1", "MAN2A1", "ST6GAL1",
    "B4GALT3", "ALG5", "B4GALT2", "MGAT5B", "ALG9", "MOGS", "FUT8", "MGAT1"
]

# run
print(enrichr(gene_list=genelist, gene_sets=gmt_filename).res2d)
```

The result of this exapmle is below with no modification.

| |Gene_set|Term|Overlap|P-value|Adjusted P-value|Odds Ratio|Combined Score|Genes|
|:----|:----|:----|:----|:----|:----|:----|:----|:----|
|0|c2.cp.kegg.v2023.1.Hs.symbols.gmt|KEGG_GALACTOSE_METABOLISM|2/26|0.021404540907508266|0.026755676134385332|11.063175747297011|42.528531249936684|B4GALT1;B4GALT2|
|1|c2.cp.kegg.v2023.1.Hs.symbols.gmt|KEGG_GLYCOSAMINOGLYCAN_BIOSYNTHESIS_KERATAN_SULFATE|4/15|6.594112017129497e-06|1.648528004282374e-05|35.723339658444026|426.1556298659424|B4GALT1;FUT8;B4GALT3;B4GALT2|
|2|c2.cp.kegg.v2023.1.Hs.symbols.gmt|KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_LACTO_AND_NEOLACTO_SERIES|3/26|0.0014262087505559746|0.002377014584259958|15.844502277163306|103.82483380017786|B4GALT1;B4GALT3;B4GALT2|
|3|c2.cp.kegg.v2023.1.Hs.symbols.gmt|KEGG_GLYCOSYLPHOSPHATIDYLINOSITOL_GPI_ANCHOR_BIOSYNTHESIS|1/25|0.19810178976233092|0.19810178976233092|6.7478991596638656|10.92467525558147|DPM2|
|4|c2.cp.kegg.v2023.1.Hs.symbols.gmt|KEGG_N_GLYCAN_BIOSYNTHESIS|46/46|5.2729211676136374e-114|2.6364605838068186e-113|10397.0|2711871.510998971|MGAT2;RPN1;MGAT4A;DDOST;RPN2;ALG12;ALG10;MGAT4B;DPM1;ALG6;STT3A;GANAB;DPAGT1;DAD1;MOGS;RFT1;MGAT5;MGAT1;ALG5;MGAT5B;ALG11;B4GALT1;MAN2A2;MAN1B1;STT3B;MAN1A1;DPM2;ALG1;B4GALT2;ALG2;MAN1A2;ALG14;ST6GAL1;ALG3;FUT8;B4GALT3;MGAT3;ALG10B;MAN2A1;ALG13;DPM3;TUSC3;ALG8;ALG9;MAN1C1;DOLPP1|

[5 rows x 8 columns]

Thank you.

**Comment by zqfang** [comment]
Thanks for your fix! I've merged into the master branch now

**Comment by 136s** [comment]
Thanks for your merge!
