### ISSUE TITLE
The bars in the center panel are misaligned.

### ISSUE THREAD

**Issue by searchlie** [zqfang/GSEApy#222]
Hi, I have always used GSEApy. Thank you for adding features so often.

By the way, I recently noticed that the bar in the center panel indicating the members of the gene set is misaligned.

Below is a comparison with the application distributed by Broad institute. The data used is [here](https://github.com/searchlie/misc).

**GSAEpy's result**
![image](https://github.com/zqfang/GSEApy/assets/28975498/ec949445-0658-473f-92b4-8b648bbb5e5f)

**GSEA_Win_4.3.2's result**
![image](https://github.com/zqfang/GSEApy/assets/28975498/44f57261-ba6f-4771-a946-e538e08cb988)

Perhaps it is just a matter of rescaling the width of the center panel.

**Comment by zqfang** [comment]
Oops, something is wrong with the bar index. I will fix this soon

**Comment by searchlie** [comment]
@zqfang 
I used the latest commit and the bars in the center panel are now correctly positioned! Thanks!
![image](https://github.com/zqfang/GSEApy/assets/28975498/c582d863-8bf7-4ef3-ac95-6075aedecbc8)
