### ISSUE TITLE
Improvement request for barplot

### ISSUE THREAD

**Issue by princessEmilyy** [zqfang/GSEApy#224]
Hi! I've been using your module and it is super convenient! 

I was wondering if there  is a way to "fix" the colors of the barplot from the results of the enrichR dataframe.

I have several comparisons and I subset a few gene sets in each, in some not all gene sets are significant and therefore are not plotted.

This causes the colors of the bars to be inconsistent across analyses e.g GO_MF_23 will be darkred in one analysis but lets say darkblue in another 

Thanks 
![download (1)](https://github.com/zqfang/GSEApy/assets/93909448/2652f6f6-74f3-4e83-8173-cee2679b6166)
![download](https://github.com/zqfang/GSEApy/assets/93909448/977ba24a-9773-4007-831e-8087ebe6f1d5)

**Comment by zqfang** [comment]
Hi, I did a patch to this function to support the feature. Now, all you need to do give a dict input, e.g.

```python
barplot( ....,  color= {'KEGG_2021_Human': 'salmon', 'MSigDB_Hallmark_2020':'darkblue'})
```
