### ISSUE TITLE
column name 'Term' in the second line

### ISSUE THREAD

**Issue by SherylShaw** [zqfang/GSEApy#230]
Hello! I've prepared the symbol and rank in R, but it seems the results from R is not very stable so I turn to GSEApy. But when I get the result, column name 'Term' is in the second line, and I cannot perform `terms = kegg.res2d.Term` next.
I wonder where my fault is and how to fix it? I'd appreciate it a lot if you could help me! 

Here's my code:

```
import pandas as pd
import gseapy as gp
import matplotlib.pyplot as plt
gene_expr = pd.read_table('GSEA/Kla/gene_expr_symbol.csv', sep=',')
gene_expr.head()

```
![gseapy1](https://github.com/zqfang/GSEApy/assets/116487212/06f5b30a-9399-41b1-9735-42085bfcf0bd)

```
kegg = gp.prerank(rnk=gene_expr, gene_sets='KEGG_2021_Human',
                     processes=4, outdir='GSEA/Kla/GSEApy/KEGG', format='png', seed=6)

kegg.res2d.head()
```
![gseapy2](https://github.com/zqfang/GSEApy/assets/116487212/2ab9db45-7e6e-40f2-b0cf-e3d2058fb946)

GSEApy version 0.9.5, Python version 3.7.1, and operating system Windows-10-10.0.22621-SP0

**Comment by zqfang** [comment]
Please update your gseapy version to the lastest. You'll get faster speed and more features. and the `term` won't be in the index column
