### ISSUE TITLE
NES values are set to 0

### ISSUE THREAD

**Issue by alegiac95** [zqfang/GSEApy#232]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import gseapy; print(gseapy.__version__)
```
```
3.7.11 (default, Jul 27 2021, 07:03:16) 
[Clang 10.0.0 ]
CPython
Darwin-22.3.0-x86_64-i386-64bit
1.0.6
```
### Expected behaviour

Hi, when running the ```prerank``` module from your library, i obtain all NES values equal to 0. I've tried to change also the dataset, but the results are still equal to 0.

Any idea why this happens?

Cheers,
Alessio

**Comment by zqfang** [comment]
What your pvals? Are all of them 1 ?

**Comment by alegiac95** [comment]
No, that's not the case, in fact it's the opposite and they're all set to 0
