### ISSUE TITLE
Incorrect position of hit in gseaplot2 like #222

### ISSUE THREAD

**Issue by 136s** [zqfang/GSEApy#248]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import gseapy; print(gseapy.__version__)
```

3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)]
CPython
Windows-10-10.0.19045-SP0
1.1.1

### Expected behaviour

In gseaplot2, the vline of hits should exist at the x coordinate where the line of RES is increasing.

### Actual behaviour

![gseaplot2](https://github.com/zqfang/GSEApy/assets/47920723/3ec58ffa-3c26-4cff-9e96-a30c40ca1d1c)

The x-coordinates of the increasing RES line do not correspond to the x-coordinates of the vline.
In the following code, `hits` are the following arrays, for example, but the rightmost orange and blue hit is at the same position (100).

```sh
[[3, 5, 6, 8, 14, 16, 18, 21, 23, 36, 47, 60, 66, 69, 77, 94],
 [2, 7, 9, 11, 12, 19, 20, 26, 30, 33, 37, 46, 50, 63, 70, 80, 92]]
```

### Steps to reproduce

```python
import gseapy as gp
import pandas as pd

rnk_url = "https://raw.githubusercontent.com/zqfang/GSEApy/master/tests/data/temp.rnk"
rnk = pd.read_table(rnk_url, header=None, index_col=0)
pre_res = gp.prerank(rnk=rnk.head(100), gene_sets="KEGG_2016", seed=6)

terms = pre_res.res2d.Term[:2]
hits = [pre_res.results[t]["hits"] for t in terms]
runes = [pre_res.results[t]["RES"] for t in terms]
fig = gp.gseaplot2(terms=terms, RESs=runes, hits=hits, ofname="gseaplot2.svg")
```

**Comment by 136s** [comment]
Hi, I tried to fix this bug. I am not sure if the fix is correct, so please check if you want.

Prior to the fix, pseudo vlines ranged from 0 to the number of terms -1, and when drawing real vlines, they were drawn broadly for each term. Therefore, fix #249 aligns the position of the hit track with the position of the mountain curve increment.
However, I can't figure out why the left edge of the pseudo vlines is off unless it is set to 1 instead of 0.

This is the new output from this fix.
![gseaplot2](https://github.com/zqfang/GSEApy/assets/47920723/b163ed22-87ec-4550-88bb-155f74913d0c)

**Comment by zqfang** [comment]
I can't figure out why this happened so far. 

The  pseudo vlines ranged from 0 to the number of terms -1 are for "making all data point in the same x range".

I need to look into this a little bit more

**Comment by zqfang** [comment]
the left edge should start with 0, to make all hits with  x range


![image](https://github.com/zqfang/GSEApy/assets/5889336/147c0104-9361-4fd9-a1d4-4048295fcead)

**Comment by 136s** [comment]
Sorry, I misunderstood the position of the mountain curve and hit track to be off by 1.
I have confirmed with GSEA 4.3.3 that your correction (the left edge should start with 0) is correct.

![enplot_HIPPO_SIGNALING_PATHWAY_HOMO_SAPIENS_HSA04390_1](https://github.com/zqfang/GSEApy/assets/47920723/7cf2f4c0-ec26-47f4-929a-d25a626db14d)
![enplot_RAS_SIGNALING_PATHWAY_HOMO_SAPIENS_HSA04014_3](https://github.com/zqfang/GSEApy/assets/47920723/d14d5489-b4a7-41d2-a34b-76573c77a344)

**Comment by zqfang** [comment]
No worries. I should not have make the mistake in the first place
