### ISSUE TITLE
`log2_ratio_of_classes`  required number of samples in the group >=3

### ISSUE THREAD

**Issue by Liripo** [zqfang/GSEApy#253]
I did not see in the documentation that the `log2_ratio_of_classes` method requires the number of samples in the group to be greater than 3, but an error message was reported when it was actually run. 

Is it because the documentation is missing or is it code bug?

![015d3f7c978b8ee79a8e8f22b98eda54](https://github.com/zqfang/GSEApy/assets/54770415/ac7b1e2c-0cde-43a8-86d2-8b519d6af529)

**Comment by zqfang** [comment]
you can calculate the log2_ratio_of_clasess and then use prerank to to the analysis


Yeah. `log2_ratio_of_classes` should not required minimum samples. I'll deal with that

**Comment by zqfang** [comment]
Hi @Liripo , The current code is correct.

The minimum number of samples is not required when `permutation_type="gene_set"`. 

Can you post your code and error message you have ?



When `permutation_type="phenotype"`, the number of samples in each group matters a lot, as the algorithm simulates the background distribution from the samples. Typically, you need at least seven samples per group for ideal results.

**Comment by Liripo** [comment]
@zqfang :
hello, This is my code:
![image](https://github.com/zqfang/GSEApy/assets/54770415/8131580c-5e9c-4fb1-a6e3-61f6bcfc85d1)
And get an error:
![image](https://github.com/zqfang/GSEApy/assets/54770415/da787346-ab89-4dc3-a2f3-f2a6fed52e6e)

My package Version is: `1.0.6`

**Comment by Liripo** [comment]
@zqfang 
I tried the sample data and extracted individual samples, but still got this error.
```py
import gseapy as gp
import pandas as pd
from gseapy import GSEA


phenoA, phenoB, class_vector =  gp.parser.gsea_cls_parser("./tests/extdata/Leukemia.cls")

gene_exp = pd.read_csv("./tests/extdata/Leukemia_hgu95av2.trim.txt", sep="\t",index_col=0)


gene_exp = gene_exp.drop("NAME",axis=1)

class_vector = [*class_vector[0:3],class_vector[-1]]

gene_exp = gene_exp.iloc[:,[0,1,2,-1]]

gs = GSEA(data=gene_exp,
    gene_sets='KEGG_2016',
    classes = class_vector, # cls=class_vector
    permutation_type='gene_set',
    permutation_num=1000, # reduce number to speed up test
    outdir=None,
    min_size=15,
    method='log2_ratio_of_classes',
    threads=4, seed= 8
)

gs.pheno_pos = "AML"
gs.pheno_neg = "ALL"
gs.run()
```

**Comment by zqfang** [comment]
You  are right. My bad.

Please use prerank instead for now. I will add a patch to fix this

**Comment by Liripo** [comment]
@zqfang 
There is only one sample in the group and an error is reported.
```py
import gseapy as gp
import pandas as pd
from gseapy import GSEA


phenoA, phenoB, class_vector =  gp.parser.gsea_cls_parser("./tests/extdata/Leukemia.cls")

gene_exp = pd.read_csv("./tests/extdata/Leukemia_hgu95av2.trim.txt", sep="\t",index_col=0)


gene_exp = gene_exp.drop("NAME",axis=1)

class_vector = [*class_vector[0:1],class_vector[-1]]

gene_exp = gene_exp.iloc[:,[0,-1]]

gs = GSEA(data=gene_exp,
    gene_sets='KEGG_2016',
    classes = class_vector, # cls=class_vector
    permutation_type='gene_set',
    permutation_num=1000, # reduce number to speed up test
    outdir=None,
    min_size=15,
    method='log2_ratio_of_classes',
    threads=4, seed= 8
)

gs.pheno_pos = "AML"
gs.pheno_neg = "ALL"
gs.run()
```
![image](https://github.com/zqfang/GSEApy/assets/54770415/d8bc5c0b-f683-4753-82c9-3ecf6b8996ca)
