### ISSUE TITLE
is it able to change the order of cls item

### ISSUE THREAD

**Issue by hfl112** [zqfang/GSEApy#261]
For example, I got two groups "Control" and "KD", I want to plot the figures using "KD vs Contrl" instead of "Contrl vs KD"

**Comment by zqfang** [comment]
use the second line of the  cls file to set the order
 for example:
```
6 2 1
# Pos Neg
Pos Neg Neg Pos Pos Neg
```

this will give you "Pos vs Neg"

**Comment by Bo-UT** [comment]
Hi, 
How to specify the comparison order in single cell data? I am using:
```
res = gp.gsea(data=adata.to_df().T, # row -> genes, column-> samples
    gene_sets=gmt,
    cls=adata.obs['treatment'], # treat and control groups
    permutation_num=1000,
    permutation_type='phenotype',
    outdir=None,
    method='s2n', # signal_to_noise
    threads= 16)
```
Thank you.

**Comment by blowinthesleep** [comment]
> Hi, How to specify the comparison order in single cell data? I am using:
> 
> ```
> res = gp.gsea(data=adata.to_df().T, # row -> genes, column-> samples
>     gene_sets=gmt,
>     cls=adata.obs['treatment'], # treat and control groups
>     permutation_num=1000,
>     permutation_type='phenotype',
>     outdir=None,
>     method='s2n', # signal_to_noise
>     threads= 16)
> ```
> 
> Thank you.

Accodring to the tutorial
># set STIM as class 0, CTRL as class 1, to make categorical
adata.obs['stim'] = pd.Categorical(adata.obs['stim'], categories=["STIM", "CTRL"], ordered=True)
indices = adata.obs.sort_values(['seurat_annotations', 'stim']).index
adata = adata[indices,:]

I believe  *categories=["STIM", "CTRL"], ordered=True* is the key

**Comment by zqfang** [comment]
set the order manually

```
# example
from gseapy import GSEA
gs = GSEA(data=gene_exp,
         gene_sets='KEGG_2016',
         classes = ['ALL', 'ALL','ALL', 'AML',........'AML'],
         # set permutation_type to phenotype if samples >=15
         permutation_type='phenotype',
         permutation_num=1000, # reduce number to speed up test
         outdir=None,
         method='signal_to_noise',
         threads=4, seed= 8)
gs.pheno_pos = "AML"
gs.pheno_neg = "ALL"
gs.run()
```
