### ISSUE TITLE
Missing wheels for Python 3.12 on PyPI

### ISSUE THREAD

**Issue by ecederstrand** [zqfang/GSEApy#265]
I tried installing the latest version of GSEApy on Python 3.12, but installing from source fails because I don't have a rust compiler installed:

```bash
python3.12 -m pip install gseapy==1.1.2
[...]
 error: can't find Rust compiler
```

I looked in PyPI but there are no pre-compiled wheels for Python 3.12. Would it be possible for you to provide those?

**Comment by zqfang** [comment]
wheels for py3.12 is uploaded. just 
```
pip install gseapy
```

let me know if pre-compiled builds are still missing

**Comment by ecederstrand** [comment]
Works now. Thanks!
