### ISSUE TITLE
gseaplot how to do to reset the label/NES etc. font size and set the FDR display

### ISSUE THREAD

**Issue by lxy04** [zqfang/GSEApy#268]
when I use the gseapy , I want to reset some font size, but I don't  know how to do, such as the title, label,NES font size
and I don't  want to show the FDR result

thanks

### Steps to reproduce

(*Please fill this in*)

**Comment by zqfang** [comment]
You can save as an editable pdf and then use Adobe Illustrator to edit the labels. It's the easiest way to me
