### ISSUE TITLE
Missing one input gene into Prerank module

### ISSUE THREAD

**Issue by wgsim** [zqfang/GSEApy#270]
GSEApy version: 1.1.4
Python version: 3.10.14
OS: MacOS, Conda - Osx 64

Thank you for developing a nice tool.
I wanna ask you to check the GSEApy version 1.1.4 prerank module.
When I try to analyze my input gene list by prerank module, it seems to be working well.
However, I found that the length of RES values is one less than my input gene list and it makes I cannot plot the graph. (it returns an error).
I tried to check the old version (1.0.4), and its length of RES values is the same as my input gene list and it works well in graphing.
Please check the prerank module of version 1.1.4.
Thanks!

**Comment by zqfang** [comment]
Would you mind sharing me your input ranking list for debugging ?
