### ISSUE TITLE
dotplot legend label error

### ISSUE THREAD

**Issue by loriglenwinkel** [zqfang/GSEApy#274]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
CPython
Linux-4.14.348-265.565.amzn2.x86_64-x86_64-with-glibc2.35
1.1.3

### Expected behaviour

correct dotplot label should be "proportion Genes in set" 

### Actual behaviour

The dotplot label currently reads ‘% Genes in set’, but the values displayed are proportions (e.g., 0.4 instead of 40%). To ensure the units match, either the legend values should be multiplied by 100 or the label should be adjusted to reflect proportions shown.”

### Steps to reproduce

gp.dotplot(enr_up.res2d, figsize=(3,5), title="Up", cmap = plt.cm.autumn_r)

**Comment by zqfang** [comment]
Good catch. Fixed now
