### ISSUE TITLE
FutureWarnings from pandas are thrown when running gseapy.dotplot() and gseapy.enrichment_map()

### ISSUE THREAD

**Issue by FischyM** [zqfang/GSEApy#283]
### Setup

I am reporting a problem with GSEApy version, Python version, and operating
system as follows:

3.9.19 (main, Mar 21 2024, 17:11:28) 
[GCC 11.2.0]
CPython
Linux-6.5.0-35-generic-x86_64-with-glibc2.35
1.1.3
2.2.2 - pandas

### Expected behaviour

Running gseapy.dotplot() and gseapy.enrichment_map() should run with no warnings.

### Actual behaviour

Running gseapy.dotplot() and gseapy.enrichment_map() throws FutureWarnings from pandas.

/project/cs-myers/MathewF/software/miniconda3/envs/netcis/lib/python3.9/site-packages/gseapy/plot.py:694: FutureWarning: The 'method' keyword in Series.replace is deprecated and will be removed in a future version.
  df[self.colname].replace(
/project/cs-myers/MathewF/software/miniconda3/envs/netcis/lib/python3.9/site-packages/gseapy/plot.py:694: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

### Steps to reproduce

```python
enrichment = gp.enrich(gene_list=gene_list, gene_sets=gene_sets, background=background, outdir=None)
res_df = enrichment.results.sort_values(['Adjusted P-value', 'P-value'])
ax_dot = gp.dotplot(res_df, column="P-value", size=6, top_term=10, figsize=(6,8), title = f"Enrichement: {treatment}", cmap="viridis_r")
nodes, edges = gp.enrichment_map(res_df, column="P-value", top_term=20)
```

**Comment by zqfang** [comment]
fixed now
