### ISSUE TITLE
[Feature request] Overlay multiple dotplots on the same ax

### ISSUE THREAD

**Issue by Puumanamana** [zqfang/GSEApy#285]
## System information

```python
import sys; print(sys.version)
import platform; print(platform.python_implementation()); print(platform.platform())
import gseapy; print(gseapy.__version__)
```
```
3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
CPython
Linux-6.1.100+-x86_64-with-glibc2.39
1.1.3
```

## Feature

I would like to make add multiple dotplots on the same figure, but it doesn't seem possible currently since each dotplot creates a new figure. 
I know it's possible to add multiple samples using the `x=` argument, but I would like to use this for another variable. So I was wondering if we could add an `ax=` argument to dotplots to reuse a preexisting figure. Here's a sample of what I'd like to do:

```python
fig, ax = plt.subplots()

dotplot(
    df1,
    x="mean_logFC",
    column="NES",
    cmap="Blues",
    ax=ax
)
dotplot(
    df2,
    x="mean_logFC",
    column="NES",
    cmap="Greens",
    ax=ax
)
```

Would it be something easy to implement? Currently, I'm able to make it work in a clunky way by modifying get_ax() to get the current figure and ax.

**Comment by zqfang** [comment]
feature added

**Comment by Puumanamana** [comment]
Awesome, thank you!
