### ISSUE TITLE
Handling Isolated Nodes in Network Visualization for 'gseapy_example'

### ISSUE THREAD

**Issue by xiiyao** [zqfang/GSEApy#292]
In the documentation 'gseapy_example', these codes are used for implementing network visualization:

```python
G = nx.from_pandas_edgelist(edges, 
                            source='src_idx', 
                            target='targ_idx', 
                            edge_attr=['jaccard_coef', 'overlap_coef', 'overlap_genes'])

……

nx.draw_networkx_nodes(G, 
                       pos=pos, 
                       cmap=plt.cm.RdYlBu, 
                       node_color=list(nodes.NES),
                       node_size=list(nodes.Hits_ratio *1000))
# draw node label
nx.draw_networkx_labels(G, 
                        pos=pos, 
                        labels=nodes.Term.to_dict())
```
### A Tiny Problem
Since ```nx.from_pandas_edgelist``` is used to construct graph `G`, isolated nodes (whose `Lead_genes` have no intersection with any other nodes and are thus not contained in `edges`) are not include in `G`, occasionally, this may lead to an error when running `nx.draw_networkx_nodes` as well as `nx.draw_networkx_labels` if isolated node exists:
```
ValueError: s must be a scalar, or float array-like with the same size as x and y
```
The issue arises because the length of `nodes` (used for setting color and size) does not match with the number of nodes in G.
### Possible Solution
Therefore, I wonder if it's proper to add annotated line like ```G.add_nodes_from(set(nodes.index) - set(G.nodes()))``` after creating G.

Excuse my intrusion, and thank you so much for your time and effort! I love GSEApy, it helped me a lot.

**Comment by zqfang** [comment]
Do you mean this codesnap ?

```
# build graph
G = nx.from_pandas_edgelist(edges,
                            source='src_idx',
                            target='targ_idx',
                            edge_attr=['jaccard_coef', 'overlap_coef', 'overlap_genes'])

# Add missing node if there is any
for node in nodes.index:
    if node not in G.nodes():
        G.add_node(node)
```

**Comment by xiiyao** [comment]
Yes, thank you. This may not be a common problem, so whether to have it take up a place in the documentation is at your wise disposal. Maybe it is good to just leave it in our issue tracker in case anyone else encounters a similar situation. Thanks again for your reply and work, it's so kind of you.
