### ISSUE TITLE
A small question about the original GSEA implementation

### ISSUE THREAD

**Issue by iseekwonderful** [zqfang/GSEApy#38]
I found that if I use signal to noise method to prerank the data, the output between GSEApy and the 
JAVA implementation from board institute are different.

e.g. 

input: p53_resample, KEGG_2016 (del 1.00 in gmt file from Enrichr) and p53.cls.

part of result

|name|GSEApy|JAVAImpl|
|---|---|---|
|DIP2A| 0.486848 |0.42881304|

Then I found the Java implementation use this method to get the stddev

``` Java
    /**
     * @return The std aa_indev of vector
     *         // Some heuristics for adjusting variance based on data from affy chips
     *         // NOTE: problem occurs when we threshold to a value, then that artificially
     *         //   reduces the variance in the data
     *         /
     *         // First, we make the variance at least a fixed percent of the mean
     *         // If the mean is too small, then we use an absolute variance
     *         /
     *         // However, we don't want to bias our algs for affy data, e.g. we may
     *         // get data in 0..1 and in that case it is not appropriate to use
     *         // an absolute standard deviation of 10 - will kill the signal.
     *         /
     */
    public double stddev(boolean biased, boolean fixlow) {

        double stddev = Math.sqrt(_var(biased));    // @note call to _var and not var
        double mean = computeset.mean;                    // avoid recalc

        if (fixlow) {
            double minallowed = (0.20 * Math.abs(mean));

            // In the case of a zero mean, assume the mean is 1
            if (minallowed == 0) {
                minallowed = 0.20;
            }

            if (minallowed < stddev) {
                // keep orig
            } else {
                stddev = minallowed;
            }
        }

        computeset.stddev = stddev;

        return computeset.stddev;
    }
```
view source: [https://github.com/GSEA-MSigDB/gsea-desktop/blob/2f44b81359917cacb9e0b113b2c540c56f38a5d7/src/edu/mit/broad/genome/math/Vector.java#L416-L453](https://github.com/GSEA-MSigDB/gsea-desktop/blob/2f44b81359917cacb9e0b113b2c540c56f38a5d7/src/edu/mit/broad/genome/math/Vector.java#L416-L453)

Could you please explain why they use a minallowed stddev?

**Comment by BioNinja** [comment]
I think the comment line answers your question.

     *         // Some heuristics for adjusting variance based on data from affy chips
     *         // NOTE: problem occurs when we threshold to a value, then that artificially
     *         //   reduces the variance in the data

it has an option to discard the low variance adjust:  boolean fixlow

**Comment by BioNinja** [comment]
Hi, @iseekwonderful , do you think it's necessary to implement this to GSEApy? I am revising the source code of GSEApy with fast speed algorithms (see v0.9.0dev branch). If yes, I could add a patch to fix variance when  mean < std
