### ISSUE TITLE
Divide by zero problem

### ISSUE THREAD

**Issue by andyjslee** [zqfang/GSEApy#40]
I am trying to the prerank function using my own data. However, I get the following error message:

`home/anaconda2/lib/python2.7/site-packages/gseapy/algorithm.py:524: RuntimeWarning: divide by zero encountered in true_divide
  choicelist = [np.sum(esnull < es.reshape(len(es),1), axis=1)/ np.sum(esnull < 0, axis=1),
/home/anaconda2/lib/python2.7/site-packages/gseapy/algorithm.py:524: RuntimeWarning: invalid value encountered in true_divide
  choicelist = [np.sum(esnull < es.reshape(len(es),1), axis=1)/ np.sum(esnull < 0, axis=1),
/home/anaconda2/lib/python2.7/site-packages/gseapy/algorithm.py:575: RuntimeWarning: Mean of empty slice.
  meanNeg = enrNull[enrNull < 0 ].mean()
/home/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
`
My weights are from 0 to 1. I get the error above after I normalize the weights to be  from -1 to 1. It doesn't matter what the weight values are, right? Do they have to include both positive and negative values?

Also, I do not get any plots generated even with more than 1500 genes. Any pointers on what I could try?

**Comment by BioNinja** [comment]
Reading at GSEA documentation they say [here](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/FAQ#Where_are_the_GSEA_statistics_.28ES.2C_NES.2C_FDR.2C_FWER.2C_nominal_p_value.29_described.3F):
> What does it mean for a gene set to have NES and nominal p-values of NaN (also shown as blanks)?
> When adjusting for variation in gene set size, we normalize permuted ES(S, pi) and the observed ES(S) for a given S, separately rescaling the positive and negative scores by dividing by the mean of the ES(S, pi) to yield NES(S, pi) and NES(S). However, when the scores of the corresponding sign are absent, the mean ES(S, pi) = 0, and the division by zero will result in NaN values both for the NES(S, pi) and NES(S) as well as for the nominal p-values that follow from these calculations. The easiest way to overcome this issue would be to increase number of permutations. If this does not help, we recommend further exploring reasons for this bias. For example, it could be caused by a large difference in the number of samples of each phenotype class. For further details, please consult the GSEA PNAS 2005 paper, sections "Multiple Hypothesis Testing" in the "Mathematical Description of Methods" and the "Supporting Text" Appendix.
> 


@andyjslee , Could you show me your commands?

**Comment by mbahin** [comment]
Hi,

I have the same problem (my 2 files are enclosed). Maybe I'm doing something wrong...
[EpenDiff_A2016.fc.sort.rkn.txt](https://github.com/BioNinja/GSEApy/files/1689810/EpenDiff_A2016.fc.sort.rkn.txt)
[ependymal.Zeisel_genes.gmt.txt](https://github.com/BioNinja/GSEApy/files/1689811/ependymal.Zeisel_genes.gmt.txt)

Basically, my ranked list are genes sorted on their fold changes from a DE experiment for mouse genes (~50k). The gene set is a set of a bit less than 500 genes.

The program is ending (the pdf image and csv file are produced) but I have the same error.

`gseapy prerank -v -r EpenDiff_A2016.fc.sort.rkn -g ependymal.Zeisel_genes.gmt -o Results`

Moreover, if I run the program with p-values, the same happens but there is no "ES" and "NES" in the report file. I enclosed the p-value file too.
[EpenDiff_A2016.pval.rkn.txt](https://github.com/BioNinja/GSEApy/files/1689812/EpenDiff_A2016.pval.rkn.txt)

Cheers,
Mathieu

**Comment by BioNinja** [comment]
It's nothing you're doing wrong @mbahin , just ignore this warning.  The lastest PR doesn't produce this warning any more.
For the pval input, I think the problem here is that there are too many genes with pval equal to 1.
