### ISSUE TITLE
Small question about heatmap

### ISSUE THREAD

**Issue by Benja1972** [zqfang/GSEApy#42]
Hello,

When gsea.call produce figures one of them is heatmap of gene set expression and in any cases (negatively or positively correlated, NES>0 or NES<0) it shows top ranked genes. I have seen in papers that heapmap presents top within core enrichment and actually it is left or right edge of ranked genes from set based on NES. How I can control heatmap output in GSEApy? 
Thank you

**Comment by BioNinja** [comment]
I guess you mean the leading edge analysis. For now, GSEApy did not implement this kind of heatmap. However, You could easily plot a new heatmap using seaborn or other packages .  I could add this new feature when I have more time.

**Comment by Benja1972** [comment]
Thank you. This is what I meant indeed. I found way how to plot heatmap of leading edges.

**Comment by Benja1972** [comment]
Hello, I would like to continue this discussion with one more question.
I did GSEApy for Reactome_2016 and got result where lots of gene sets have pval and fdr equal to 0. Top 50 of them were finished with pictures of enrichment graphs (by setting graph_num = 50). It is fine. But question is how top50 were selected? From result table (see attached) I can conclude that some gene sets with pval,fdr=0 and position below 50 have bigger ES and NES then those from top of the list.  
Thank you for help

![selection_183](https://user-images.githubusercontent.com/11920879/38549484-64bb0ad2-3cb4-11e8-8682-418a6a76653e.png)
![selection_184](https://user-images.githubusercontent.com/11920879/38549485-64e37314-3cb4-11e8-85a7-61575b8e35e2.png)

**Comment by BioNinja** [comment]
@Benja1972 , top graph_num were ranked by FDR values.

**Comment by Benja1972** [comment]
Thank you, I got it now. Sorry my fault

**Comment by zqfang** [comment]
leading edge genes are added to the output now #56
