### ISSUE TITLE
Use GSEApy with Dataframe, dict, etc without having to make hard copies of the output

### ISSUE THREAD

**Issue by EmanuelGoncalves** [zqfang/GSEApy#43]
Hi,

Is it possible to use GSEApy without requiring to have the output exported to files/folders?

Thanks,

**Comment by zqfang** [comment]
Sorry, @EmanuelGoncalves , It does not support yet. However, you could create temp files using python's `tempfile` module which cleans up all things after running your analysis.

**Comment by dllahr-foghorntx** [comment]
I'll second this request.

**Comment by zqfang** [comment]
Well, I'll look into that

**Comment by zqfang** [comment]
@EmanuelGoncalves , @dllahr-foghorntx 
Hi, guys,
         this feature has been implemented to v0.9.5 branch. There will be no any outputs to your disk if you set outdir=None. If this is useful for you, please install v0.9.5 branch

**Comment by dllahr-foghorntx** [comment]
Thank you!

**Comment by zqfang** [comment]
0.9.5 has been released.

**Comment by EmanuelGoncalves** [comment]
Thank you
