### ISSUE TITLE
ssGSEA sample_norm_method="custom" produces error

### ISSUE THREAD

**Issue by dllahr-foghorntx** [zqfang/GSEApy#45]
Hello

First, thank you very much for making this tool!  I was trying to use Single Sample GSEA (`ssgsea`) and I was looking to use the option `sample_norm_method="custom"` and I couldn't see a way to provide the custom ranking, so I was looking through the code and I noticed on lines 556-558: (https://github.com/zqfang/GSEApy/blob/d2439dc08c28fc966a555fb3c5cfaf30042a7162/gseapy/gsea.py#L556-L558
of `gsea.py` that in the handling of the `custom` case in the method `norm_samples` the return variable `data` is not created, causing it to immediately throws an error if you call with this option e.g.
```python
ss2 = gseapy.ssgsea(g.data_df, gene_sets=geneset_output_file, verbose=True, 
    sample_norm_method="custom")
UnboundLocalError: local variable 'data' referenced before assignment
```

Did you mean to have `data = dat` in this section and then when the user uses the `custom` option they provide the ranking?

Thank you in advance!

**Comment by dllahr-foghorntx** [comment]
quick update - I modified https://github.com/zqfang/GSEApy/blob/d2439dc08c28fc966a555fb3c5cfaf30042a7162/gseapy/gsea.py#L556-L558
to add `data = dat` after line 557 and it appears to work.

**Comment by zqfang** [comment]
Thanks for you help. fixed now
