### ISSUE TITLE
y-axis in enrichment score plot is all zeros

### ISSUE THREAD

**Issue by ghost** [zqfang/GSEApy#46]
Hello

I'm doing a trivial "hello world" example of calculating enrichment score - I chose my gene sets to exactly match the 49 most down-regulated genes.  When I look at the enrichment score plot, the y-axis numbers are all zero:
![example_dn ssgsea](https://user-images.githubusercontent.com/36932252/43088172-87647bba-8e6f-11e8-879a-22f278f78d65.png)

The code I used to generate this:
`ss2 = gseapy.ssgsea(g.data_df.iloc[:, :1], gene_sets=geneset_output_file, verbose=True, format="png", outdir="temp2")`

I believe for example the top-most tick mark should be 0.5.

Any ideas about this?

Thanks in advance!

**Comment by zqfang** [comment]
this is weird, the y-axis ticks should be automatically determined by matplotlib. I'll check this later
