### ISSUE TITLE
use of tempfile.TemporaryDirectory incompatible with Python 2.7

### ISSUE THREAD

**Issue by dllahr-foghorntx** [zqfang/GSEApy#50]
Hi, I noticed that in this commit:
https://github.com/zqfang/GSEApy/commit/a8fe55ebf692180e7e0b39d3b7cc852b512b372a#diff-73d289c8bfd27b90e234684d8d793e6cL8
(line 8)
that the code now uses tempfile.TemporaryDirectory, which is not present in Python 2.7, causing the code to break if using Python 2.7.

There are couple workarounds for this:
https://stackoverflow.com/questions/19296146/tempfile-temporarydirectory-context-manager-in-python-2-7

**Comment by zqfang** [comment]
this is because I'm planning to drop 2.7 support in next release.

**Comment by dllahr-foghorntx** [comment]
Ahh, OK!
