### ISSUE TITLE
odd memory behavior use multiple processes

### ISSUE THREAD

**Issue by ghost** [zqfang/GSEApy#51]
I've spent the better part of day investigating this and I'm stumped, so I'll mention it in case you have any ideas.  I'm running single sample GSEA using processes = 8.  I run it first on my data in a dataframe with 200 genesets, and then on another 200 genesets etc. in a for loop (code attached).  I'm not saving any data in the for loop, and yet the memory usage goes up - I've repeated several times and the for each iteration the memory usage is (%):  `1.4, 2.7, 3.9, 5.1` (starts at 0.1, goes down to 3.8 after running gc after the loop finishes).

A couple interesting points:

- increasing the size of my dataframe causes the numbers above to increase, but same pattern
- re-running the calculation immediately causes this pattern of memory usage:  `5.0, 5.0, 5.0, 5.0` (starts at 3.8, ends at 3.8)

The second point suggests it is not a memory leak, perhaps the GC is not properly cleaning up until the pool starts up again?

I tried running `del` on various objects and rewriting the code in various ways, without any visible effect on the memory usage pattern above.

Code I used is to illustrate all the above attached as jupyter notebook:
[07 illustrate memory leak.ipynb.gz](https://github.com/zqfang/GSEApy/files/2234046/07.illustrate.memory.leak.ipynb.gz)

**Comment by zqfang** [comment]
sorry for replying late. I'm back from vacation. I will take a look into this

**Comment by zqfang** [comment]
now, use joblib to do parallel computing
