### ISSUE TITLE
TypeError when running gseapy.gsea() with P53 example

### ISSUE THREAD

**Issue by billy-kong** [zqfang/GSEApy#53]
Python version : 2.7
GSEApy version : 0.9.4

Hi.
When using the P53 example provided, I am getting 'TypeError':
![image](https://user-images.githubusercontent.com/43195614/45402714-0890fc00-b692-11e8-8970-318ca4e662d2.png)

Thank you so much in advance!

**Comment by zqfang** [comment]
Could you try GSEApy v0.9.5 with python 3?
