### ISSUE TITLE
All the gene sets got Zero score at 562

### ISSUE THREAD

**Issue by armadillocommander** [zqfang/GSEApy#54]
Hi,

After I updated the gseapy to 0.95, although the data in gseapy.gsea.gene_set.report.csv looks good, in the generated score map, ALL the gene sets got 0 score at 562, no matter how the covered genes are distributed in the list. 

Can anyone check this issue? Thanks!

[ko00030.gsea.pdf](https://github.com/zqfang/GSEApy/files/2390218/ko00030.gsea.pdf)
[ko00190.gsea.pdf](https://github.com/zqfang/GSEApy/files/2390219/ko00190.gsea.pdf)
[ko00230.gsea.pdf](https://github.com/zqfang/GSEApy/files/2390220/ko00230.gsea.pdf)
[ko00250.gsea.pdf](https://github.com/zqfang/GSEApy/files/2390221/ko00250.gsea.pdf)

**Comment by zqfang** [comment]
Hi, @armadillocommander ,  I think your input expression data  is the same for all gene_sets. `rank_list_metric` only inspect your input expression data. That's why all the gene sets got 0 rank score at 562

**Comment by armadillocommander** [comment]
@zqfang Yes your are right, I misunderstood the ranking metric scores. Thanks!
