### ISSUE TITLE
Leading edge genes

### ISSUE THREAD

**Issue by nwieder** [zqfang/GSEApy#56]
Hi and thanks for the python implementation of GSEA!
Maybe I just overlooked this, but is there a way to get hold of the leading edge genes for enriched gene sets for further downstream analysis?

Thanks,

Nico

**Comment by zqfang** [comment]
Actually, there's a complicated way to do this. Well, I could add the leading genes to the output file.

**Comment by nwieder** [comment]
Yeah, I realized now that you can generate it from the result dictionary. I think, adding it to the output would be really useful!

**Comment by nwieder** [comment]
Here is a code snippet the extracts the leading edges and stores them in a dictionary:

res_dict = pre_res.results
RNK = pre_res.rnk.sort_values('stat', ascending=False)
fdr_cutoff = 0.05
ledge_up = {}
ledge_down = {}
for gs in res_dict:
    if res_dict[gs]['fdr'] < fdr_cutoff:
        h_idx = res_dict[gs]['hits_indices']
        RES = res_dict[gs]['RES']
        es = res_dict[gs]['es']
        if es > 0:
            idx = np.where(h_idx == np.where(
                np.isclose(RES, es, 1e-6))[0][0])[0][0]
            ldg_pos = h_idx[:idx]
            ledge_up[gs] = ','.join(RNK.iloc[ldg_pos].index)

        if es < 0:
            idx = np.where(h_idx == np.where(
                np.isclose(RES, es, 1e-6))[0][0] + 1)[0][0]
            ldg_pos = h_idx[idx:]
            ledge_down[gs] = ','.join(RNK.iloc[ldg_pos].index)

I'll close the issue, thanks.

**Comment by zqfang** [comment]
Thanks very much. This is what I need.
