### ISSUE TITLE
Question about ssGSEA FDR

### ISSUE THREAD

**Issue by TeenyL** [zqfang/GSEApy#57]
Hello, 
My questions is about ssGSEA FDR. 
In my results, there are several FDR = 0. Is there any way to get the actual FDR value?

![screen shot 2018-10-14 at 22 47 43](https://user-images.githubusercontent.com/27300910/46922105-900cba80-d004-11e8-864e-7f012c7da01f.png)

Thanks

**Comment by zqfang** [comment]
FDR and pval is not reliable if you set permu_num > 0. It's not a useful value for ssGSEA @TeenyL
