### ISSUE TITLE
run speed and heatmaps in 0.9.4 vs 0.9.8

### ISSUE THREAD

**Issue by meono** [zqfang/GSEApy#61]
I noticed performance issues after upgrading to 0.9.8. I was wondering if that is to be expected. I think performance in 0.9.8 also suffers from lack of scaling with number of processes allowed (processes=1 seems pretty similar to  processes>1), but I haven't really confirmed this.

Here is a sample code based on docs, if anyone would like to replicate and report back:
```
import pandas as pd
import gseapy as gp
import time
gene_exp = pd.read_table("./data/P53.txt")
for processes in range(1, 4):
    start_time = time.time()
    gs_res = gp.gsea(data=gene_exp, # or data='./P53_resampling_data.txt',
                     gene_sets='./data/temp.gmt', # enrichr library names
                     cls= './data/P53.cls', # cls=class_vector
                     permutation_type='phenotype',
                     permutation_num=100, # reduce number to speed up test
                     outdir=f'./test/{gp.__version__}/{processes}',  # do not write output to disk
                     method='signal_to_noise',
                     processes=processes,
                     format='png'
                    )
    print(f'with {processes} process(es):\t {round((time.time() - start_time), 3)} seconds')
```
(Use the data folder under test from the package for inputs.)
It produces
```
with 1 process(es):	 133.614 seconds
with 2 process(es):	 76.917 seconds
with 3 process(es):	 71.06 seconds
```
for v0.9.4 on my laptop. v0.9.8 version took over 20min with 1 process and I didn't continue.

With the heatmaps (hsa05330 set in this example), there are far more genes shown for 0.9.8 version (lower), compared to 0.9.4(upper). Is there a new argument to use here?
![image](https://user-images.githubusercontent.com/8055398/48850242-8404dd00-eda8-11e8-9ced-574d69212c75.png)

Any comment is appreciated.

**Comment by zqfang** [comment]
Sorry that I've turned off the multi-processing capacity for plotting heatmap. So, the performance are compromise. 

For the second question, it seems that all input genes have been shown. Let me fixed that

**Comment by zqfang** [comment]
Could you try to install the lastest PR. I need to update some other code before the next release @meono

**Comment by meono** [comment]
Ah, ok. I can see it works quite fast without plots. Also the heatmaps show the right genes now.
Thanks @zqfang.
