### ISSUE TITLE
Error when using .enrichr with "KEGG_2016".

### ISSUE THREAD

**Issue by RBenRocks** [zqfang/GSEApy#62]
I am using "KEGG_2016" as gene set through gseapy.enrichr(), but keep getting the following error:

`'<=' not supported between instances of 'str' and 'float'`

Using "GO_Biological_Process_2018", "GO_Biological_Process_2017", "KEGG_2015" works.

**Comment by zqfang** [comment]
Could you show me the full trace error message?

**Comment by zqfang** [comment]
These is weird, I can not reproduce the error. Could you show me the first 5 row of your gene_list?

**Comment by jacobkimmel** [comment]
Hey @zqfang, I'm getting the same error.

It seems to involve some interaction between the gene list and gene set.
I can get results just fine for instance querying `GO_Molecular_Function_2018`, but `GO_Biological_Process_2018` throws this error.
Likewise, `GO_Biological_Process` works just fine with other gene lists.

Hope that help!

**Comment by zqfang** [comment]
Thanks @jacobkimmel . This is helpful
