### ISSUE TITLE
Input genes with their DE already calculated

### ISSUE THREAD

**Issue by ddomingof** [zqfang/GSEApy#67]
I have a set of genes with their differential expressions already calculated and I would like to know whether it is possible to input this sort of data (instead of raw expression + class vector) to the gsea main function?

Thank you and regards!

**Comment by zqfang** [comment]
Do you mean you want to run gsea with preranked gene list? If then, try ``prerank`` function. If not, use ``enrichr`` function with gene list only.

**Comment by ddomingof** [comment]
Exactly! thank you. I overlooked it!

**Comment by asifemon** [comment]
I have little doubt here. I am guessing the input for prerank gene list is basically genes with their fold change, right? And, in the end what we get with this prerank function is to see if certain pathways are up/down regulated considering their positive or negative cumulative fold change?

**Comment by zqfang** [comment]
In breif, yes. The ``preranked`` means that you can defined the ranking by yourself. e.g. fold change, signal2noise.
