### ISSUE TITLE
conda dockerfile

### ISSUE THREAD

**Issue by moxgreen** [zqfang/GSEApy#68]
Hi,
I'm using the gseapy docker image provided by https://quay.io/repository/biocontainers/gseapy.
I found it thanks to https://bioconda.github.io/recipes/gseapy/README.html

I have some minor problem running the image so I would like to improve it a bit but I can not find the related Dockerfile. Can you help me?

**Comment by zqfang** [comment]
Docker file are generated by bioconda build system. see here: https://bioconda.github.io/build-system.html
