### ISSUE TITLE
the value of nes，pvalue and fdr can‘t achieve reproducibility

### ISSUE THREAD

**Issue by huchua** [zqfang/GSEApy#70]
I run the same data five times and get 5 different value of nes，pvalue and fdr.  The results were shown as follow.
![GSEA_replicate](https://user-images.githubusercontent.com/46836781/55372090-11182980-5533-11e9-9e54-b03a73cdc9f7.png)

**Comment by zqfang** [comment]
nes, pval, fdr depends on null distribution. However, random permutation will produce slightly different null distribution. That's why

**Comment by zqfang** [comment]
now, fixed the issue
