### ISSUE TITLE
enrichment test for two ranked gene lists

### ISSUE THREAD

**Issue by MingBit** [zqfang/GSEApy#72]
hallo,

I'm doing enrichment test for two ranked gene lists. I couldn't find the appropriate function to do so as the parameter **gene_sets** always need to be a .gmt file.

I thought that p value and enrichment scores might be affected by manually creating a gmt file as only one gene set will be in the this customised gene sets file.

So I'm actually looking for a _signed ks test_ [https://github.com/franapoli/signed-ks-test](url) from this package... 

any ideas??? many thanks! :)

**Comment by zqfang** [comment]
You could input custom gene sets. see #60  
yes, it will be problematic for FDR and NES values when only one gene set in gmt file. I will see what I can do
