### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by liugaocn** [zqfang/GSEApy#75]
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.
            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:
                if __name__ == '__main__':
                    freeze_support()
                    ...
            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.

I have been getting this message all day. I did exactly the same as your documentation suggested. All files were prepared just fine.

**Comment by zqfang** [comment]
What's your command used?

**Comment by liugaocn** [comment]
I used exactly the same code your provided in your example. But it didn't work. 
Then I just did:
if __name__ == '__main__':
    gs_res = gp.gsea(data=data_s,
                     gene_sets='KEGG_2016',
                     cls = cls_list,
                     permutation_type='phenotype',
                     permutation_num=100,
                     outdir='test/gsea_kegg',
                     no_plot=True,
                     processes=4,
                     method='signal_to_noise',
                     format='png')
    print(gs_res.res2d.head())
and this worked. They say on windows I have to add if name==.. code.

**Comment by zqfang** [comment]
Good to know that your problem was solved. By the way, you should  increase your permutation_num to get better results. e.g 1000
