### ISSUE TITLE
ssgsea fails with pandas multiindex

### ISSUE THREAD

**Issue by ac3957** [zqfang/GSEApy#76]
When the input data to ssgsea is a multi-indexed pd.DataFrame, I get a "TypeError: not all arguments converted during string formatting" within the runSamples process.

This can be resolved by dropping the multi-index first, then adding it back after - but I assume there's a better solution.

**Comment by zqfang** [comment]
For now, ssgsea module did not support multi-indexed Dataframe. So, what's your purpose that you need multi-indexed dataframe input for ``ssgsea``

**Comment by ac3957** [comment]
Understood. Multi-indexed DataFrames are commonly used to track meta-data across samples.

Not saying this needs to be fixed, but it would be good to put somewhere in the documentation that this feature is not supported. It took me a while to figure out the source of the error message above.
