### ISSUE TITLE
gseaplot generates nothing at all

### ISSUE THREAD

**Issue by liugaocn** [zqfang/GSEApy#77]
I used  the method you demonstrated in your documentation.

**with code like:**
from gseapy.plot import gseaplot
terms = gs_res.res2d.index
gseaplot(gs_res.ranking, term=terms[0], **gs_res.results[terms[0]])

but nothing really happend. Then i checked its datatype, it returned NoneType. What I am gonna do if I want to plot on myself, since I generated thousands of them.

**Comment by zqfang** [comment]
You have to use ``ofname`` to save your figure:

    gseaplot(...ofname="test.pdf")

**Comment by liugaocn** [comment]
What a relief. haha. I am finally getting a hang of this. By the way it is highly advised to update your documentation. Thanks for the package and your answers.

**Comment by zqfang** [comment]
Yeah, you are right.

**Comment by liugaocn** [comment]
Last time, I didn't try again. 
When I try today, I get errors again:

terms = gs_res.res2d.index
gseaplot(gs_res.ranking, term=terms[83], ofname="test gene apoptosis.pdf")

I get errors like
``TypeError: gseaplot() missing 5 required positional arguments: 'hits_indices', 'nes', 'pval', 'fdr', and 'RES'``

Do i have to set up all these parameters manually? I guess it is explicit.
Besides, what are hits_indeces and RES?

**Comment by liugaocn** [comment]
I just succeded. haha.
