### ISSUE TITLE
ssGSEA score depends on other samples

### ISSUE THREAD

**Issue by jorisvdhaar** [zqfang/GSEApy#78]
Hi,

When running ssGSEA (see code below), I found out that the enrichment score for a given gene set in a given sample depends on the other samples in the expression data. In other words, if the input data includes expression data for patient A, B, C and D, I obtain different results for gene set X on patient A as compared to when using only input data of patient A and B.

Toy example:
Input patients: A,B,C,D
Output for gene set X: 0.5,-0.25,0.33,-0.30

Input patients: A,B
Output for gene set X: 0.33,-0.20

This surprises me, as Barbie et al state in their methods that enrichment scores are calculated separately for every gene set in every sample. Do you have an explanation for this?

Cheers,
Joris

```
ss = gp.ssgsea(data=expr,
               gene_sets=genesets_dict,
               outdir='/PATH/TO/RESULTS/',
               sample_norm_method='rank', # choose 'custom' for your own rank list
               permutation_num=0, # skip permutation procedure, because you do need it
               no_plot=True, # skip plotting to speed up
               min_size=1,
               processes=8, format='png')
output = ss.res2d.copy(deep=True)
```

**Comment by zqfang** [comment]
Do you mean ES value or NES value?

**Comment by jorisvdhaar** [comment]
I see, it indeed happens in the normalization. I missed that part, thank you!
