### ISSUE TITLE
ssGSEA missing p value and FDR

### ISSUE THREAD

**Issue by Gimpomane** [zqfang/GSEApy#79]
Hello,

I would like to verify whether the genes in my gene-set (.gmt file) are enriched within the top scores of my data file (.txt file). 

So when I run ssgsea as suggested:
```
gseapy ssgsea -d expression.txt -g gene_sets.gmt -o test
```
I get the output files containing both raw and normalized enrichment scores (ES) but neither p-value nor FDR. The graphical output does not contain those values as well.

Example 1:
![gsea_out1_inked](https://user-images.githubusercontent.com/32650632/58369142-b24dab80-7ef6-11e9-900b-6a16f633aee6.jpg)

Example 2 with data heavily represented at the top:
![gsea_out2_inked](https://user-images.githubusercontent.com/32650632/58369155-e45f0d80-7ef6-11e9-8297-7706a5554b6d.jpg)

When I run ssgsea with the permutation procedure:
```
gseapy ssgsea -d expression.txt -g gene_sets.gmt -o test -n 1000
```
an additional file is generated containing the p-value and FDR, but they are not shown in the graphics. Additionally it is not suggested to use the permutation procedure for publication, correct?
Is it a bug that those values are missing or am I doing something wrong?

Thanks in advance,
Gimpomane

**Comment by zqfang** [comment]
Hi, @Gimpomane , you are doing nothing wrong. You only need ES or NES value if ``ssgsea`` was used.   The original ssGSEA alogrithm will not give you pval or FDR, so, please ignore the gseaplot generated by ``ssgsea``. It's useless  

I guess that you need ``prerank`` tool to test whether your gene-set are enriched within the top scores of your data file .

One more thing, if you'er seeking for ssgsea with p-value output, please see here: https://github.com/broadinstitute/ssGSEA2.0

**Comment by Gimpomane** [comment]
Thank you very much for you the quick reply.

I am using your ```prerank``` tool now and it works like a charm.

**Comment by ac3957** [comment]
As a follow up question, should we ignore this warning then?

`# run permutation procedure and calculate pvals, fdrs`

`self._logger.warning("run ssGSEA with permutation procedure, don't use these part of results for publication.")`

**Comment by zqfang** [comment]
Your results would be fine when permuation_num=0
