### ISSUE TITLE
Is there some reason that the version of package on bioconda isn't update yet?

### ISSUE THREAD

**Issue by Tim0thy1** [zqfang/GSEApy#81]
Hi,zqfang.
I compare the code on bioconda  with github and find some different.  For example,  on bioconda
1 . the name of function is gsea_plot not gseaplot
2. a param of  gsea_plot(gseaplot?) function  is hit_ind not  hits_indices

**Comment by Tim0thy1** [comment]
By the way. Can I generate my GSEA plot  in command line? The output just have heatmap figure.

**Comment by zqfang** [comment]
You have to update GSEApy version (0.9.13) using bioconda.  
Yes, you could generate GSEA plot using command line. By default, the output contains heatmap and gseaplot, unless you use ``--no-plot``

**Comment by manzt** [comment]
I'm having a similar issue. Using GSEApy (0.9.8), enrichr.py calls `pd.read_table` instead of `pd.read_csv`.
