### ISSUE TITLE
Unable to run gseapy after a conda installation

### ISSUE THREAD

**Issue by agroppi** [zqfang/GSEApy#85]
I have installed gseapy by using conda as follow : 
```
mkdir /myworkingdir/Gseapy
conda install -c bioconda gseapy --prefix /myworkingdir/Gseapy
```

But after that I'm unable to launch gsea ...
There is no gseapy  executable in the whole directory and subdirectories ?

**Comment by zqfang** [comment]
Have you try 

    gseapy gsea ….

?

**Comment by agroppi** [comment]
Solved :)
It was a problem of conda and python version.
Re installed with conda/python3
and it works
Thanks

**Comment by zqfang** [comment]
Good
