### ISSUE TITLE
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 78, saw 6

### ISSUE THREAD

**Issue by bhupendra069** [zqfang/GSEApy#88]
I am trying to read a table from a url but while executing this table, I am getting "error tokenizing data.
url1 = 'https://github.com/neurospin/pystatsml/tree/master/datasets/iris.csv'
url_filename=pd.read_csv(url1)
print(url_filename)

I tried read_html also but I am getting second column additional with all NAN values.

**Comment by zqfang** [comment]
I think you probably need to download the csv file first and read
