### ISSUE TITLE
Strange Error in Pre-rank module

### ISSUE THREAD

**Issue by RobertWell** [zqfang/GSEApy#90]
Sorry, I really meet some problem in operating this module.
Code:

import gseapy as gp
import pandas as pd
rnk = pd.read_csv("./gsea/edb/gsea_data.gsea_data.rnk", header=None, sep="\t")
print(rnk.head())

pre_res = gp.prerank(rnk=rnk, gene_sets='KEGG_2016',
                     processes=4,
                     permutation_num=100, # reduce number to speed up testing
                     outdir='0103test/prerank_report_kegg', format='png')

I import the 'gsea_data.gsea_data.rnk', and it shows the same table as in your documents.
but the gp.prerank it's not working at all.
The console reports a RuntimeError: 
An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Could you give me some advice?

**Comment by zqfang** [comment]
Are you using Windows? If yes, you may try
```
if __name__ == '__main__':
     pre_res = gp.prerank(......)
```

**Comment by RobertWell** [comment]
It works! Thanks!
