### ISSUE TITLE
Running GSEA with large gmt file

### ISSUE THREAD

**Issue by 10mubeen** [zqfang/GSEApy#91]
Hi, I'm trying to run GSEA with a gmt file that has just over 3000 gene sets. For the parameters, I have the max_size set to 3000, the method is the default, processes=4 and have dropped the number of permutations to 10. Running this results in a memory error for me. Is there an upper limit on the number of gene sets my gmt file can contain? And is there anyway for me to get around this problem (e.g., changing the parameter settings, running in batches, etc.)? Any help would be greatly appreciated!

Thank you!

**Comment by zqfang** [comment]
Would you show me the command you are using?

**Comment by 10mubeen** [comment]
Hi, thanks for getting back to me! Just an update- I saw in a previous issue you suggested using gseapy version 0.9.3. I tried that and the memory error is now gone. 

GSEA is nonetheless taking a long time to run so hopefully once it's successfully done, I'll go ahead and close the issue. 

FYI I am running it using this function:

def perform_gsea(gene_exp: str, gene_set: str, cls: str, output_dir: str):
    """Run GSEA on a given dataset and gene set.

    :param gene_exp: file with gene expression data
    :param gene_set: file with pathway gene sets
    :param phenotype_class: cls file containing information on class labels
    :param output_dir: output directory
    """
    return gseapy.gsea(
        data=gene_exp,
        gene_sets=gene_set,
        cls=cls, 
        max_size=3000,
        permutation_type='phenotype',
        permutation_num=10,  
        outdir=output_dir,
        no_plot=True,  # Skip plotting
        processes=4,
        format='png',
    )
 
Thanks again!

**Comment by zqfang** [comment]
Well, when you choose permutation_type='phenotype', it takes a long time to compute on the big permutated gene_exp matrix. Sorry for that, I don't have a quick solution for this now.
