### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by boiarsky18** [zqfang/GSEApy#95]
Hi, 

I'm getting wildly different results with the gsea method when changing the seed. Have 380 samples, using rna-seq data as expression data. As an example, im setting the seed=4 and getting apical function fdr .0000000, then i set the seed=10 and get apical junction fdr = .89. I assume this isn't expected behavior? Can you please let me know what may be going on? Thanks!

**Comment by zqfang** [comment]
This is unexpected behavior, could you post the code you used?
