### ISSUE TITLE
Inconsistent get_library_name and gp.enrichr for Yeast database

### ISSUE THREAD

**Issue by fossatiA** [zqfang/GSEApy#98]
### Setup

I am analyzing some yeast data and I noticed a inconsistency between the libraries retrieved by get_library name() and the enrichr API.

```python
import sys; print(sys.version)
3.7.4 (default, Aug 13 2019, 15:17:50
import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Darwin-16.7.0-x86_64-i386-64bit
import gseapy; print(gseapy.__version__)
0.9.17
```

### Expected behaviour

Raise an Exception not sys.exit(1)

### Actual behaviour

Not validated Enrichr library name provided
Hint: use get_library_name() to view full list of supported names(base) 
sis.exit(1)

### Steps to reproduce

```python
 nms = ['CDC28']
    for gene_libr in gp.get_library_name(database='Yeast'):
        outfile = 'test'
        enr = gp.enrichr(gene_list=nms,
                         gene_sets=gene_libr,
                         outdir=outfile,
                         cutoff=1,
                         verbose=True)
```
not working all the .*AutoRIF.* plus others. 
I noticed that in line 340 of [https://github.com/zqfang/GSEApy/blob/master/gseapy/enrichr.py](enrich)

```python
        if len(gss) < 1:
            sys.stderr.write("Not validated Enrichr library name provided\n")
            sys.stdout.write("Hint: use get_library_name() to view full list of supported names")
            sys.exit(1)
```

I propose to change it with

```python
        if len(gss) < 1:
            sys.stderr.write("Not validated Enrichr library name provided\n")
            sys.stdout.write("Hint: use get_library_name() to view full list of supported names")
            raise LookupError
```

I know you could catch sys.exit() but it would be more pythonic to raise an Exception.

**Comment by zqfang** [comment]
@fossatiA  Thanks, I think need to set
```python
gp.enrichr( ...
                    organism='yeast'
                   ...)
```

But you are right, this is not intuitive with additional  keyword `organism`

**Comment by fossatiA** [comment]
Worked like a charm, thanks. I'm closing this issue
